### ISSUE TITLE
Introduce yourself 

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall19#1]
Hi everyone - 

I thought I'd kick off a post where everyone can reply with an introduction to themselves so we can get to know each other. 

**Tell us what brought you to this course and any other details you care to share.**

A little bit about myself - I'm a web programmer and educator, living in Arlington, MA. In addition to this course, I also teach [DGMD E-28](/e28) and [CSCI E-15](https://hesweb.dev/e15). I've also worked with students completing their capstones in the DGMD program.

In the past, I've taught at Wellesley, UPenn, and UMiami. When working in industry I was the head developer for an online e-commerce store. 

More about my background here: [susanbuck.net](https://susanbuck.net)

All in all, I love creating things with code and teaching others how to do the same.

Looking forward to getting to know you all!

**Comment by RGPhD** [comment]
Hello Professor Susan Buck, Teaching Fellows and Classmates; it is nice to meet you.
 
I am taking this class as a candidate for the Masters of Liberal Arts in Digital Media Design at Harvard Extension School (HES).  I took CSCI E-12: Fundamentals of Website Development in Spring 2019 and CSCI S-3: Introduction to Web Programming Using JavaScript this summer.  I am also taking DGMD E-20: Modern and Mobile Front End this semester.
 
I am new to web development, so I am a bit nervous for this backend/server side PHP course.  However, I did take a few computer science courses in the 90’s and completed a Fundamentals of Coding undergrad course at Arizona State University (ASU) in 2017 that touched on server side.  Further, HES’s online classes fit very well into my hectic schedule.  I am currently an ASU Faculty Affiliate in Biomimicry, a Professor at Personal Professors Online Academy and I periodically teach undergraduate courses for ASU.  Additionally, I teach American Red Cross, lifestyle medicine, geriatric wellness, health and biogerontology kinesiology classes online and in person at Senior University.
 
My previous education is as diverse as my current teaching.  I just completed my fourth diploma at ASU (Spring 2019), a Graduate Certificate in Law Enforcement Administration.  I am also ABD away from my second Doctorate, the Doctor of Behavioral Health degree.  Moreover, I completed a Master of Arts in Criminal Justice and Criminology in 2014, a Master of Science in Aging and Lifespan Development in 2011 and a Post-Doc Graduate Certificate in Gerontology in 2009.  In addition, I have a PhD and MEd in Education/Athletic Administration and a Master of Science in Kinesiology that I finished in the 90's.  I am also currently working on a Doctor of Metaphysics at The University of Sedona. 
 
What started as an avenue to participation in collegiate athletics has turned into my life’s passion as a Lifelong Learner and Lifelong Educator.  After retiring as a professional basketball player and tenured professor, I began my pursuit to becoming a Multidisciplinary Educator and Interdisciplinary Scholar.  When I am not teaching or studying, I love to stay busy volunteering.  I started volunteering for Harvard University DCE Accessibility Services my first semester at HES.  Please connect with me on any or all of my social accounts https://scholar.harvard.edu/drrobelyngarcia/social.  I look forward to learning with and from all of you in the course and on GitHub!
 
Robelyn

**Comment by shcantrell** [comment]
Hello, Susan.

I too, am a Susan, just followed by "Cantrell," instead  :). This will be my last course before I tackle the capstone project (eeeek!) in pursuit of a Masters of Liberal Arts in Digital Media Design.

I started as a graphic designer over 15 years ago, which only evolved into web design and is now inching toward web development (what that last part means exactly, I am still figuring out). The bulk of my career involved working in the public sector, making it no coincidence that I currently work within IT at the Mass. Executive Office of Health and Human Services (EOHHS).

I am certain you are aware that Drupal is one of the most used website content management systems when it pertains to the academic and government sectors. That being said, EOHHS dove in headfirst with its goal of a new IT intranet presence. Unknowingly, we stood-up and developed a Drupal 7 site on a Windows environment, realized our mistake and migrated to an in-house Linux environment (built our own LAMP stack), only to start over in Drupal 8 when the project was upgraded from just an IT intranet site to an intranet site for the entirety of the Secretariat. You have no idea how desperate we are to figure out how to setup a GIT version control workflow on our local desktops!

So...that leads me here...to "WEB PROGRAMMING FOR BEGINNERS WITH PHP"- the backbone of Drupal.

I am quite sincere when I say, I look forward to the class.

Susan Cantrell

**Comment by shcantrell** [comment]
> Hi everyone -
> 
> I thought I'd kick off a post where everyone can reply with an introduction to themselves so we can get to know each other.
> 
> **Tell us what brought you to this course and any other details you care to share.**
> 
> A little bit about myself - I'm a web programmer and educator, living in Arlington, MA. In addition to this course, I also teach [DGMD E-28](/e28) and [CSCI E-15](https://hesweb.dev/e15). I've also worked with students completing their capstones in the DGMD program.
> 
> In the past, I've taught at Wellesley, UPenn, and UMiami. When working in industry I was the head developer for an online e-commerce store.
> 
> More about my background here: [susanbuck.net](https://susanbuck.net)
> 
> All in all, I love creating things with code and teaching others how to do the same.
> 
> Looking forward to getting to know you all!


Hmmmm - Is this how we reply to a post?

I was going to ask if we were going to use Introze? :)

**Comment by RGPhD** [comment]
Dear Susan @shcantrell,

I am also in pursuit of a Masters of Liberal Arts in Digital Media Design.  *Congratulations* on making it to the Capstone!

Robelyn @RGPhD

**Comment by susanBuck** [comment]
@RGPhD - I'm quite impressed by your depth of experience!

@shcantrell - I don't typically use Introze for online courses, but maybe I should be. : )
Regarding replying to posts - I don't think it's necessary to include the copy from the previous post as we can see it in the thread. Doesn't hurt, but not necessary. 👍
And next week we'll be tackling a git workflow from your computer, so hopefully that will answer some questions for you!

**Comment by shcantrell** [comment]
@RGPhD - So....exactly what do you want to be when you grow up? At the rate you're going, anything you want! Goodness you have a lot of credential under your belt.
- Let me actually survive capstone before you start congratulating me - lol. Also, my experience has been all trial by fire - ouch, ouch, ouch, ick, ouch. Hehe.

@susanBuck - Okay, replying to posts using mentions is much smarter - duh.
- I'm ready...gooooOOOOO GIT version control!

**Comment by Janeece** [comment]
I am taking this course to fill my last elective for my Information Management Systems Masters. After this, just the Capstone left. 

I live in Huntington Beach, CA and work for an aerospace company as a project manager in the regulatory and safety group.

Looking forward to interacting with everyone.

**Comment by philyuska** [comment]
Howdy all,

I live in Winchester MA and am taking this course for professional development. I'm a network engineer and have worked in and around the web infrastructure for many years.

I haven't any formal training but I've worked with PHP and MySQL in the past (I'm a bit of an addict to tell you the truth). Version control is a bit of a mystery to me so I am looking forward to learning to use GitHub as well as learning some good programming practices.  

Cheers,
Phil

**Comment by MPVaccaro** [comment]
Hello all.

I'm **Mary Vaccaro**.  

I just got accepted as a candidate for a Masters in Digital Media Design at the Extension School, so I am now officially on my way.

In addition to taking these classes, I work full time for a Cannabis Business-to-Business trade show, [CWCBExpo](https://www.cwcbexpo.com/),\* where I do graphics and photography.

In the evenings,  I run a small [Kung Fu and Tai Chi school](http://nabisumartialarts.com/) in Manhattan.

I am very excited to take this particular class.  In the spring, I took the CMS class and learned the beginnings of building websites with Joomla, Wordpress and **Drupal**.  Although I found Drupal very tough and difficult to understand in the 4 weeks allocated to it, I loved it!  

I loved it so much that I am currently building on my class-made Drupal site with the goal of transferring my decade old Kung Fu sites to the Drupal format.

I am doing the Drupal install and updates manually.  **I did not learn  _Drush_ and _Composer_.**  Adding to that, I have **php error messages in the installation**.

An example of a **Drupal php error message**:

```The rebuild_access setting is enabled in settings.php. It is recommended to have this setting disabled unless you are performing a rebuild.```

I just this morning learned **Markdown.**  I've never used **GitHub** before.

There is so much I don't know that this class seems like it will be just what I need.

I live in NYC but will be coming up to Boston for our CWCBExpo in late October, and I hope to pick up my new Harvard ID and possibly meet some local fellow students then.  

\*  _If anyone wants free passes to the Expo, let me know._

**Comment by lkratzberg** [comment]
Hi! My name is Lyndsey Kratzberg and I am pursuing a Graduate Certificate in Programming. I am currently a high school computer science teacher. The classes I teach are dual credit at the local community college, which requires me to further my education with graduate credit hours. My background is in Accounting, not programming, and I spent 11 years in the corporate business world before transitioning to teaching a couple of years ago. I absolutely love the career change and love learning what I can do with programming.

**Comment by Matt49** [comment]
Hello All,

My name is Matt Grififng, and I live in Waltham, MA.  I am a graphic designer, front-end developer, and photographer. I have had my own business for 11 years, and I have also worked part-time in those roles for the National Park Service and DS Solidworks. 

These days my web design projects usually involve modifying the CSS of existing WordPress themes. I'm interested in learning best practices, improving my workflow, and building a solid foundation from which to learn PHP. I have taken courses that touched on JavaScript and PHP but never gained enough momentum with them to keep up the practice.

I find the concrete nature of programming a nice balance to the more subjective world of graphic design. I enjoy outdoor activities like cycling and skiing, but most days my exercise consists of walking my dog - and playing chase with her.

**Comment by janenycxo** [comment]
Hi Everyone,

My name is Jane Yeh and I am from Queens, NY.  I am taking this course as part of the Info. Mgmt. System Masters and after this semester, I will have 3 more courses to go (including my capstone).

I don't have too much experience with programming but I have taken CSCI E-15 (intro) in the Fall of 2018 and DGMD E-25 (WCM) in the Spring of 2019 and enjoyed it very much. 

Looking forward to this semester!
Jane

**Comment by jeremiahazurin** [comment]
Good Afternoon! 

I'm an undergraduate from Washington, DC. I'm also new to programming. Prior to college, I took time off to backpack and cycle overseas, and also worked in human rights research and international education. I returned to college a little later in life and am now in my senior year. I will be joining the Foreign Service with the US Department of State after graduation this May.

**Comment by jclough14** [comment]
Hello!
I am Jonathan Clough and I live in the Bay Area of Northern California.  I am currently pursuing the Masters in Liberal Arts degree in Digital Media Design.  I am enjoying learning html, but I am finding that my design flair is stuck in the 80s!  So I need to catch up to the times.  Or just wait for the designs to get back in style.
-Jon-

**Comment by anyav77** [comment]
Hi, my name is Anya Zinoveva.  This is my last course toward the Graduate Certificate in Website Technologies.  I'm also starting an application process to the ALM in Digital Media Design. 

I come from a graphic design/web design background, but I have years of experience working in IT.  I'm trying to bridge a gap between education and work experience.  I have been looking forward to this class for a long time, and I'm excited about it.

Anya

**Comment by sethkhan** [comment]
Greetings.

My name is Shais.  I'm from Orange County, CA.  I help manage PE funds that have significant exposure to technology. I got tired of talking to software engineers and not understanding technology stacks, so I am getting more programming experience.  HES has been very helpful and has improved my understanding vastly.

I look forward to getting to know you this semester and if you are in the OC, let's meet up...always good to meet HES classmates.

Best,

Shais Khan

**Comment by nhillsbos** [comment]
Hello,

My name is Nick. I've worked as a freelance designer and illustrator for a while, but I'm trying to move into web development. I've been attending HES since last fall. With this course, I should be able to get my Front End Web Developer certificate.

I'm excited to learn more about building SPAs with vue.js!

**Comment by kking1204** [comment]
Hello, I work as a media producer for the Extension School. I've been working in web development for ten years, and you'd think I'd be better at it by now! :D 
I'm excited to learn more PHP and to gain some tangential skills along the way.

**Comment by susanBuck** [comment]
Thanks everyone for your introductions - I enjoyed learning about your backgrounds and seeing where everyone is "tuning in" from!
