### ISSUE TITLE
Variable to input data

### ISSUE THREAD

**Issue by MPVaccaro** [susanBuck/e2-fall19#100]
I think I'm missing something very basic, but I've been thinking all day and not finding the answer:

How do I convert the output (result) of a variable, for example ```$newMove```,  into a string datatype that I can input into the data base?

**Comment by susanBuck** [comment]
Something like this...

```php

$newMove = [...code here that gets/calculates the move...]

$this->app->db()->insert('games', [
    'newMove' => $newMove,
    # [...etc. for other fields...]
]);
```

? 

In terms of making it a String data type specifically, can you tell me more about what `$newMove ` is to begin with? (Tip: [PHP's gettype](https://www.php.net/manual/en/function.gettype.php) function can tell you what the data type is if you're unsure).

**Comment by MPVaccaro** [comment]
Thank you!
That's exactly what I needed.

**Comment by susanBuck** [comment]
Great! : )

Going to close this thread but feel free to re-open/start a new thread if needed.
