### ISSUE TITLE
Local server: create alias error - 'vhosts' is not recognized

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e2-fall19#101]
I'm trying to create an alias for vhosts, but I got an error.  Am I missing a step?

```
C:\cmder-master\config
λ vhosts=notepad c:\xampp\apache\conf\extra\httpd-vhosts.conf
'vhosts' is not recognized as an internal or external command,
operable program or batch file.

C:\cmder-master\config
λ
```

**Comment by susanBuck** [comment]
Few things to try:

1. Run `alias` to see your lists of aliases - is `vhosts` added?

2. Manually edit `c:\cmder-master\config\user_aliases.cmd` to add your alias.

3. Restart Cmder

**Comment by anyav77** [comment]
Thank you! It helped.
