### ISSUE TITLE
Getting this error: sudo chmod 777 cache chmod: cache: No such file or directory

### ISSUE THREAD

**Issue by lindsaymshepard** [susanBuck/e2-fall19#104]
LindsayShepard@Lindsays-MBP p4 % sudo chmod 777 cache
chmod: cache: No such file or directory

**Comment by susanBuck** [comment]
Can you run the command `ls -la` (show directory contents) within your `p4` directory and share the output?

**Comment by lindsaymshepard** [comment]
LindsayShepard@Lindsays-MBP p4 % ls
777	MyApp

**Comment by lindsaymshepard** [comment]
LindsayShepard@Lindsays-MBP p4 % ls -la
total 8
drwxr-xr-x   4 LindsayShepard  admin  128 Dec  9 12:57 .
drwxr-xr-x  13 LindsayShepard  admin  416 Dec  9 12:54 ..
-rw-r--r--   1 root            admin    1 Dec  9 12:56 777
drwxr-xr-x  16 LindsayShepard  admin  512 Dec  9 12:57 MyApp
LindsayShepard@Lindsays-MBP p4 %

**Comment by susanBuck** [comment]
It looks like you created a `p4` directory, and then within it you ran the "create project" command:

```
composer create-project --prefer-dist susanBuck/e2framework MyApp
```

This resulted in a new directory called `MyApp`, nested within the `p4` directory. 

**To fix, I suggest the following steps:**

Navigate to the root of your e2 directory.

Remove the existing `p4` directory (and its nested `MyApp`):

```bash
rm -rf p4
```

While still in `e2/` run the "create project" command again, this time swapping `p4` in for `MyApp`:

```
composer create-project --prefer-dist susanBuck/e2framework p4
```

This should create a `p4` directory which you can move into and run the `sudo chmod 777 cache` command.

**Comment by lindsaymshepard** [comment]
thank you! that worked
