### ISSUE TITLE
Error writing /Applications/XAMPP/etc/extra/httpd-vhosts.conf: Permission denied

### ISSUE THREAD

**Issue by nbandach** [susanBuck/e2-fall19#109]
Hi, I am trying to set up Virtual Host for my p4 project and I keep getting this error:
![Screenshot 2019-12-12 at 22 14 56](https://user-images.githubusercontent.com/6833462/70749682-23d33700-1d2d-11ea-845d-316189c37d19.png)
I saw here: http://write.flossmanuals.net/command-line/nano/ that it was enough to press enter but when I do, I get this error:
![Screenshot 2019-12-12 at 22 15 03](https://user-images.githubusercontent.com/6833462/70749714-33eb1680-1d2d-11ea-83f6-ddb634a35c0a.png)
I tried every command in there, and the error persists. On Cancel, I get prompted again whether I want to save the changes (which I do), and the same all over again.
Any clues why this happens now?  I re-watched the videos but there was nothing around this issue, I tried to Google this but the suggestions seem not to work for me.

**Comment by susanBuck** [comment]
Because it's a permissions error, try prefixing your nano command with sudo, which means *"Run this command as the admin."*

```bash
$ sudo nano /Applications/XAMPP/etc/extra/httpd-vhosts.conf
```

**Comment by nbandach** [comment]
Thanks. It gives me the same error thought all the process (command not found). Do you know why this can happen? 

Natalias-MacBook-Air:public natbandach$ hosts
-bash: hosts: command not found
