### ISSUE TITLE
P1 README.md link

### ISSUE THREAD

**Issue by janenycxo** [susanBuck/e2-fall19#11]
For project 1, system requirements state the 
application must be accessible via http://p1.yourdomain.com and the application must exist as a directory within in your e2 git repository (e.g. e2/p1).

For the README.md file I entered http://p1.yourdomain.com then changed it to http://your domain.com/e2/p1 for final commit. Both links are accessible, would you suggest I change it back to http://p1.yourdomain.com and resubmit quiz with the http://p1.yourdomain.com format?

Sorry for being silly, I just want to be sure before submitting any additional changes. Thank you!

**Comment by susanBuck** [comment]
You can just update the README file with the correct URL (http://p1.yourdomain.com). No need to re-submit.

**Comment by janenycxo** [comment]
Ok, I will do that. Thank you!

**Comment by janenycxo** [comment]
I have corrected the link to reflect http://p1.yourdomain.com. I have submitted project 1 quiz last night before 9pm (with a confirmation time stamp) however the page has a resume quiz button. Is that supposed to happen?

**Comment by janenycxo** [comment]
As the quiz appears it has not retained my initial submission, I have submitted the answers again to prevent any submission errors from the course site. Apologies if duplicate. Err on the side of caution.

**Comment by susanBuck** [comment]
Hi @janenycxo -

Not sure it was not retaining your initial submission. On my end, I see two submissions:

One at Sept 14 @ 8:48pm
One at Sept 17 @ 5:03pm

If this happens again in future assignments, just email me directly (susanbuck@fas.harvard.edu) and I can reach out to Canvas support on your behalf.
