### ISSUE TITLE
Week 15 assignment, Question 11 - Which view file would be served?

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall19#111]
Hi everyone,

In the **Week 15 assignment, Question 11** asks:

> Given the following return statement from a controller, which view file would be served?
```php
return $this->app->view('recipe.ingredients');
```

The correct answer should be:
```
/views/recipes/ingredients.blade.php
```

However, I had an error in the possible answers, so this was not one of the options listed.

I've since corrected the question, but some of you have already completed the assignment. 

**Because of this, I'll be dropping this question from the final scoring.**

Apologies for the confusion, and hat tip to the student who drew it to my attention!

**Comment by MPVaccaro** [comment]
Thank you! I spent a long time on that question and finally just picked something, since nothing seemed right...
