### ISSUE TITLE
Error when inputting id in search bar

### ISSUE THREAD

**Issue by jclough14** [susanBuck/e2-fall19#112]
I was trying to set up the redirect when someone inputs an id directly in the search bar and I get the following error.  For example, the search bar says "p4.loc/result?id=2" (which exists), and I try and modify it to 222 (which does not exist).

Warning: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\e2\p4\vendor\symfony\var-dumper\Dumper\AbstractDumper.php:182) in C:\xampp\htdocs\e2\p4\vendor\susanbuck\e2core\src\App.php on line 203

Any thoughts?

**Comment by susanBuck** [comment]
The `headers already sent` error typically occurs when something is echo'd/print'd to the page before doing a redirect.

[I suspect the cause is this dump statement...](https://github.com/jclough14/e2/blob/master/p4/app/Controllers/AppController.php#L23)

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any problems are still pending.
