### ISSUE TITLE
MAX ID

### ISSUE THREAD

**Issue by MPVaccaro** [susanBuck/e2-fall19#113]
This code correctly gives me the info from the database according to its id:

```dump($this->app->db()->findById('games', 132));```

How do I get it to return the results from the __MAX__ id?  The id is auto-incrementing, and I only want the most recent one, which would be the MAX id.

**Comment by susanBuck** [comment]
For this we can write a custom SQL statement to be executed by the app db [`run` method](https://hesweb.dev/e2/notes#/php/e2framework/database?jump=emrunem).

Here's an example I worked up in ZipFoods to demonstrate:

```php
 public function practice3()
{
    $lastProductAdded = $this->app->db()->run('SELECT * FROM products ORDER BY id DESC LIMIT 1')->fetch();

    dump($lastProductAdded);
}
```

Ref: [AppController ln 135](https://github.com/susanBuck/e2/blob/master/zipfoods/app/Controllers/AppController.php#L135)

**Comment by MPVaccaro** [comment]
Thank you!
I appreciate the detailed and concise answers.
Everything I have asked in this forum has been explained by you previously in the videos and class notes, however, I didn't understand what it meant until you have pointed it out with your clear replies.

**Comment by susanBuck** [comment]
np! I find there's often a difference between reading/seeing something and actually implementing it - it often takes all 3 steps before things start to click. : )
