### ISSUE TITLE
Problems with Images Displaying

### ISSUE THREAD

**Issue by MPVaccaro** [susanBuck/e2-fall19#115]
When I'm loading images on my local server webpages, there are several images that fail to display.  

The images that fail to display have been images that I have edited and converted to .png and .jpg from other file types, typically .psd, .eps and .ai.  They have been reduced to about 800px wide, and are less than 500 kb in size.  The 'alt text' displays in lieu of the image, and I am having no problem with html links. _(When I swap in an alternate image, the alternate image displays normally.)_

These same images have been used in other web and social media postings with no problem.

How can I find out what is preventing a particular image from displaying?

**Comment by susanBuck** [comment]
Hi @MPVaccaro Can you share the URL where we can see the broken images? Also, can you point to which files in your repo where the images are being loaded?

**Comment by MPVaccaro** [comment]
For my project, when an image wouldn't display, I simply replaced it with a different image, so there are no broken links on my project.

So now I'm wondering, how do I analyze why a particular image does not "work." The images that didn't display had been converted from other file types to .jpg or .png. I was able to use those same images on social media and other postings, but they wouldn't work with this project.  I'm guessing there was something in the image file history that was not being recognized by the .html code. 

Is there is a way to analyze an image file to tell why it doesn't display?  Or is there a standard in html code that prevents certain images from displaying?

**Comment by susanBuck** [comment]
> Is there is a way to analyze an image file to tell why it doesn't display? 

If I had an image that wasn't loading, I'd start by trying to access the image directly in the browser.

For example, if i was trying to load an image like `<img src='/images/example.jpg'>` via a page at `http://p4.hesweb.xyz` I would attempt to load `http://p4.hesweb.xyz/images/example.jpg` directly in the browser.

If the image didn't load, I'd know the path was correct, but something was wrong with the image.

If I got a 404 not found error, I'd know the path was incorrect.

I'd also look at the size of the image itself, confirming it was a "healthy" size for the image (sounds like you did that).

Finally, I'd try and and see if it loaded in different programs (e.g. Photoshop, Preview on Mac, etc.). I could even try opening it directly in the browser via *File: Open File...*.


> Or is there a standard in html code that prevents certain images from displaying?

None that I'm aware of. As long as it's a valid image (e.g. .png, .jpg, .gif) it should load.

Are you able to reproduce the problem by exporting an image and attempting to load it on your app? Or is it random?

**Comment by kking1204** [comment]
Are the file permissions set correctly on your image file? I had to fix mine after I uploaded it to my server.  It looked fine on my local app, but got a broken image icon on my live site.
