### ISSUE TITLE
Cant Send Results on Redirect?

### ISSUE THREAD

**Issue by conornap** [susanBuck/e2-fall19#118]
Hi folks, 
perhaps someone can tell me what I'm doing wrong here. I calculate the results of my game and it persists to the database just fine, but when I send the results along via the redirect it comes back as null. I made a separate page called "results" and I can get it to load just fine there, but the point is the show the results on the home page. Obviously the results aren't making it to the index, but I'm not sure why.

**Code in AppController**
```
        // Define results to be sent to DB
        $results = [
            'winner' => $winner,
            'roll' => $roll,
            'choiceA' => $choiceA,
            'choiceB' => $choiceB
        ];

        $this->app->db()->insert('p4', $results);

        return $this->app->redirect('/', ['results' => $results]);
    }
```
**Code in Index**
```
    {{ $app->old('result')}}
    {{ dump($results)}}
```
**View on local**
<img width="1239" alt="Screen Shot 2019-12-15 at 9 10 35 PM" src="https://user-images.githubusercontent.com/35695725/70874258-62603000-1f7f-11ea-9dd6-af583b5722db.png">

**Comment by susanBuck** [comment]
FYI Cloning your app locally now to take a look. Will report back on what I find.

**Comment by susanBuck** [comment]
It looks like the code you have on Github is not yet updated, because in that version you're redirecting to a results page, not the index.

But, I think I was able to spot the problem from the snippets you provided above:

In this line, you call it `results` (plural): 
```php
return $this->app->redirect('/', ['results' => $results]);
```

Then, when you attempt to retrieve it, you call it `result` (singular):

**Comment by conornap** [comment]
Thanks, so much, I've got it working now.
