### ISSUE TITLE
Current date/time

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e2-fall19#120]
How can I access the current date and time in templates or appController?

I looked up Symphony forum and tried 
```php
dump($today);
```
and
```html
<input type="hidden" id="timestamp" name="timestamp" value="{{$today}}">
```

but it didn't work.

**Comment by susanBuck** [comment]
Back when we looked at [built-in php functions](https://hesweb.dev/e2/notes#/php/functions-built-in) we saw some examples of using [PHP's date function](https://www.php.net/manual/en/function.date.php) to generate date/times.

In the [Week 4, Part 2 video](https://www.youtube.com/embed/EQ9qefPOuwQ?rel=0&showinfo=0) at the 5:15 mark I walk through the date function.

**Comment by anyav77** [comment]
Yes, it helped.  Thank you so much!
