### ISSUE TITLE
Permission denied (publickey) issue

### ISSUE THREAD

**Issue by jeremiahazurin** [susanBuck/e2-fall19#124]
Hello, just adding this separate issue on my Permission denied (publickey) from [here](https://github.com/susanBuck/e2-fall19/issues/121#issue-538828639)! I can't connect to my production server. I'm on a Mac.

**Comment by susanBuck** [comment]
When was the last time you were able to SSH into your server?

Has anything changed since then?  (e.g., new computer, added/changed existing SSH keys)

**Comment by susanBuck** [comment]
Issue resolved via Zoom, so closing this thread. Feel free to re-open/start a new thread if it happens again.
