### ISSUE TITLE
Incorrect PHPMyAdmin login

### ISSUE THREAD

**Issue by jeremiahazurin** [susanBuck/e2-fall19#126]
Does this mean that my log-in to PHPMyAdmin is incorrect?
```
root@e2:/var/www/html/e2/p4# php console App fresh
"Executing App\Commands\AppCommand@fresh"
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in /var/www/html/e2/p4/vendor/susanbuck/e2core/src/Database.php:22
Stack trace:
#0 /var/www/html/e2/p4/vendor/susanbuck/e2core/src/App.php(100): E2\Database->__construct('p4', 'users', 'e2', 'jeremiahazurin', 'utf8mb4')
#1 /var/www/html/e2/p4/app/Commands/AppCommand.php(14): E2\App->db()
#2 /var/www/html/e2/p4/app/Commands/AppCommand.php(45): App\Commands\AppCommand->migrate()
#3 /var/www/html/e2/p4/vendor/susanbuck/e2core/src/App.php(80): App\Commands\AppCommand->fresh()
#4 /var/www/html/e2/p4/console(12): E2\App->console(Array)
#5 {main}
  thrown in /var/www/html/e2/p4/vendor/susanbuck/e2core/src/Database.php on line 22
```

I'm trying to find my log-in but for some reason it's not in ```e2/zipfoods``` so if this is the case, is there another way to retrieve the pw and log-in?

**Comment by jeremiahazurin** [comment]
Also, should I be running from ```/e2``` or ```/e2/p4```? I've noticed that I've had to go back and forth between the two even here

**Comment by susanBuck** [comment]
Because this error is happening on production, can you share the contents of your production  `/e2/p4/.env` file?


> Also, should I be running from /e2 or /e2/p4

Commands are a project-specific thing, so they should be run within the project (`/e2/p4`)

**Comment by jeremiahazurin** [comment]
```
APP_NAME='p4'
APP_URL='http://p4.jae2.me'

DB_HOST='localhost'
DB_NAME='p4a'
DB_USERNAME='e2'
DB_PASSWORD='jeremiahazurin'
```

I had to do "p4A" because i messed up when creating the first one in myphpadmin

**Comment by jeremiahazurin** [comment]
I just found [this](https://askubuntu.com/questions/321903/resetting-forgotten-phpmyadmin-password). To be safe, would this be legitimate and not disrupt my p4 work that I've already done?

**Comment by susanBuck** [comment]
Two things:
1. This is not a phpmyadmin related thing - we're not using phpmyadmin on the production server. The problem is your application is unable to create a connection with the MySQL database.
2. The error is not indicating there's a problem with your password, so I don't think it's necessary to reset it.

To help you troubleshoot, could you give me access to your production server? [Instructions here...](https://hesweb.dev/e2/notes#/appendix/instructor-server-access)

**Comment by jeremiahazurin** [comment]
Done! thank you!

**Comment by susanBuck** [comment]
I'm in... Will report back on what I find out.

**Comment by susanBuck** [comment]
When I ran `php console App fresh` I received a different error than the one you shared above:

```
root@e2:/var/www/html/e2/p4# php console App fresh
"Executing App\Commands\AppCommand@fresh"
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'e2'@'localhost' (using password: YES) in 
[...etc...]
```

Key part of this error:  **Access denied for user 'e2'@'localhost' (using password: YES)**
I.e. something is wrong with the username and/or password.

To debug this, I went into MySQL mode ([per the instructions here](https://hesweb.dev/e2/notes#/php/databases/production?jump=create-a-new-database)) and I ran a SQL command to have it show me the users that existed:

```
mysql> select User from mysql.user;
+------------------+
| User             |
+------------------+
| debian-sys-maint |
| mysql.session    |
| mysql.sys        |
| root             |
+------------------+
4 rows in set (0.00 sec)
```

As you can see, there are 4 users, but none of them are `e2`.

To address this I followed the [steps to create a new user](https://hesweb.dev/e2/notes#/php/databases/production?jump=create-a-new-mysql-user):

```
mysql> CREATE USER 'e2'@'localhost' IDENTIFIED BY 'jeremiahazurin';
Query OK, 0 rows affected (0.01 sec)

mysql> GRANT ALL PRIVILEGES ON * . * TO 'e2'@'localhost';
Query OK, 0 rows affected (0.00 sec)

mysql> FLUSH PRIVILEGES;
Query OK, 0 rows affected (0.02 sec)
```

Then I tried running `fresh` again, getting a different error this time:

```
root@e2:/var/www/html/e2/p4# php console App fresh
"Executing App\Commands\AppCommand@fresh"
"Migration complete."
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'p4a.users' doesn't exist in 
[...]
```

From this we can infer that we were able to successfully connect to the database. But, now it can't find the table `users` within the `p4a` database.

To understand why this was happening, I looked at your migration code in [AppCommand.php](https://github.com/jeremiahazurin/e2/blob/master/p4/app/Commands/AppCommand.php) and found that when you are creating the table you're calling it `Users`:

```php
     $this->app->db()->createTable('Users', [
            'title' => 'varchar(255)',
            'content' => 'text',
        ]);
```

But then later, when you insert data in your seed, you call the table `users`:

```php
 $this->app->db()->insert('users', $app);
```

You need to fix this locally, the sync the changes to Github -> production, and try again.

Also: Confirm your migrations/seeds are running locally before trying on production.

**Comment by jeremiahazurin** [comment]
THANK YOU!!!!!!!!!!!!!!!!!!!! i appreciate it! so far the migrations and seeds ran cleanly. THANK YOU!!!
