### ISSUE TITLE
Individual Page not showing

### ISSUE THREAD

**Issue by jeremiahazurin** [susanBuck/e2-fall19#128]
```
List of Registrants Here
<ul>
    @foreach($apps as $thisApp)

    <li><a href='/post?id={{ $thisApp[' id']}}'> {{$thisApp['title'] }}</li></a>

    @endforeach
</ul>
```

Fortunately my links show up but for some reason they don't direct to an individual page. They're all "active" but when i hover over the links, i see an "error on line 11" message in the ```/cache``` folder. Also it's red? 
<img width="836" alt="Screen Shot 2019-12-17 at 21 11 42" src="https://user-images.githubusercontent.com/16971379/71049912-d4687e80-2111-11ea-850d-9c9b265a25d7.png">

**Comment by anyav77** [comment]
It looks like the issue with the quotation marks.
Try "id" instead of 'id'

**Comment by jeremiahazurin** [comment]
<img width="1130" alt="Screen Shot 2019-12-17 at 21 53 13" src="https://user-images.githubusercontent.com/16971379/71051892-a84ffc00-2117-11ea-821b-9615c9be443c.png">
Thanks, but I tried that and it gave me an error:

```
Notice: Undefined index: id in /Applications/XAMPP/xamppfiles/htdocs/e2/p4/cache/a111441d37c9feeeb6a41d51e65b6826937f13ef.php on line 11
">
```

**Comment by anyav77** [comment]
I meant the outer quotes should stay singular, and the inner quotes should be double:
```blade
'/details?id={{ $thisApp["id"]}}'
```

**Comment by jeremiahazurin** [comment]
Thanks! But still getting the same error

**Comment by anyav77** [comment]
Could you provide a screenshot?

Also, try to reverse the quotes:
```blade
"/details?id={{ $thisApp['id']}}"
```

**Comment by jeremiahazurin** [comment]
<img width="1130" alt="Screen Shot 2019-12-17 at 22 05 55" src="https://user-images.githubusercontent.com/16971379/71052471-67f17d80-2119-11ea-8719-99b7bba67f5b.png">
Thanks! Above is a SS with the reversed quotes

**Comment by jeremiahazurin** [comment]
ok so progress...apparently one issue was an extra space in ```{{$thisApp['title'] }}```. will trouble shoot to continue because now i'm having another issue with still showing individual ID pages.

**Comment by anyav77** [comment]
You also have an extra space in ' id'
It should be:
```blade
{{$thisApp['id'] }}
```

**Comment by jeremiahazurin** [comment]
Thanks! my next issue is:

```
public function details()
    {
        $userId = $this->app->param('id');

        $thisApp = $this->app->db()->findbyId('users', $userId);
        dump($userId);

        return $this->app->view('details');
    }
}

```

in the above code, still can't get indiv ID pages. still trudging through but i think it's the pesky method again ($thisApp vs $app vs $apps)

**Comment by jeremiahazurin** [comment]
@susanBuck

**Comment by jeremiahazurin** [comment]
hi, i submitted my assignment just to get whatever points i can salvage but i still would like to know what the error was. thanks!

**Comment by susanBuck** [comment]
@jeremiahazurin Looking at the [current code in your `details` method](https://github.com/jeremiahazurin/e2/blob/master/p4/app/Controllers/AppController.php#L36), it shows this:

```php
 public function details()
    {
        $userId = $this->app->param('id');

        $thisApp = $this->app->db()->findById('users', $userId);
        return $this->app->view('users', ['users' => $thisApp]);
    }
```

This returns an error:
```
 View [users] not found.
```

This is because there is now view `users`:

![image](https://user-images.githubusercontent.com/237711/71109864-28b44280-2194-11ea-86af-817ed33fd241.png)

**Comment by jeremiahazurin** [comment]
i see, i see. thank you. i thought i had to put the phpmyadmin table name (in my case, users) in, not the view file. darn. thank you!
