### ISSUE TITLE
old text not staying

### ISSUE THREAD

**Issue by jeremiahazurin** [susanBuck/e2-fall19#129]
```html
<form method='POST' action='/save-new-applicants'>
    <label for='title'> Name:</label>
    <input type='text' id='title' name='title' value='{{$app->old(" title")}}'>
    </br></br>

    <label for='content'> Email:</label>
    <textarea id='content' name='content'> {{$app->old(' content')}}</textarea>
    </br></br>
    <p>

        <button type='submit'> Register
        </button>

</form>
```

i'm trying to keep old text from staying in if there's an error in the validation but it's not showing. The data, however, is stored. How can i get the text to persist, too?

**Comment by AntonieKowal** [comment]
I'm not sure if this is causing the problem, but it appears that there is whitespace in the string you are passing to the ```old()``` method. That may be worth investigating, I hope it fixes your issue!

**Comment by jeremiahazurin** [comment]
Hmm, interesting. Thank you!

**Comment by susanBuck** [comment]
Cleaned up the spacing and tested it locally - the following worked for me:

```php
<input type='text' id='title' name='title' value='{{ $app->old("title") }}'>
```

And:
```php
<textarea id='content' name='content'>{{ $app->old('content') }}</textarea>
```
