### ISSUE TITLE
Error with Terminal

### ISSUE THREAD

**Issue by jeremiahazurin** [susanBuck/e2-fall19#13]
I have a Macbook and I'm having trouble with git. I'm sure it's on my computer since I think I messed something up when trying to [customizing the command line](https://hesweb.dev/e2/notes#/command-line/mac-terminal) with ~/.bashrc.

**Problem**
<img width="653" alt="Screen Shot 2019-09-16 at 02 04 15" src="https://user-images.githubusercontent.com/16971379/64936928-4afd9380-d826-11e9-94cf-dc4260649fe1.png">

Where do I go from here?

**Comment by jeremiahazurin** [comment]
Ah, I think it just means that I haven't installed Git, which I just did.

But when starting terminal, does anyone else have this message? Is this normal? I feel like I didn't do the ~/.bashrc customization thing properly...
<img width="697" alt="Screen Shot 2019-09-16 at 02 13 05" src="https://user-images.githubusercontent.com/16971379/64937248-8a78af80-d827-11e9-88d4-bdd601afcbbf.png">

**Comment by susanBuck** [comment]
Hi @jeremiahazurin The message you're seeing when you start terminal is expected based on the [Mac terminal customization](https://hesweb.dev/e2/notes#/command-line/mac-terminal) notes I shared.

What is not normal is that the message is showing twice. : ) Does it do that every time you start terminal?

**Comment by jeremiahazurin** [comment]
Yes, it always shows twice.

**Comment by susanBuck** [comment]
There are other config files terminal could be reading from, and one of those might also be sourcing `~/.bashrc` which would explain why it's loading twice.

To see if this is true, undo what the notes said to do regarding sourcing `.bashrc` from `.bash_profile`.

Edit ~/.bash_profile:
```
sudo nano ~/.bash_profile
```

Remove these lines:
```
if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi
```

Close and re-open Terminal. 

Are you now seeing the message just once? If yes, it means some other file was already sourcing `.bashrc`. If that's the case, you can track down what file is doing it, or just leave it as is. 

If you're no longer seeing the message at all, we can assume `.bash_profile` was the only file sourcing `~/.bashrc`, and you can revert the above changes. Then, I would look closer at what you have in the `~/.bashrc` file itself to see why it's repeating. Any possibility you paste in the template I provided twice?

**Comment by susanBuck** [comment]
Sorry, missed this part of your question in my above response:

No, the double message should not impact your use of Terminal. More just annoying/curious. :)

**Comment by susanBuck** [comment]
I'm going to go ahead and close this issue out since I haven't heard back, but feel free to re-open or keep the discussion going if you're still having this issue.
