### ISSUE TITLE
Practice site not loading photo.

### ISSUE THREAD

**Issue by jeremiahazurin** [susanBuck/e2-fall19#15]
Hi, I thought I had solved the problem I had with a photo not loading but I encountered it again. I'm at the step where I'm [restarting Apache so that my VirtualHost changes takes effect](https://hesweb.dev/e2/notes#/production-server/production-domains). 
![Screen Shot 2019-09-16 at 20 14 16](https://user-images.githubusercontent.com/16971379/65001763-ddea0c80-d8be-11e9-8e95-36488862bf26.png)
On my localhost, my image displays properly. But on my site with the domain that I purchased on namecheap, it doesn't (as reflected in the photo above). I'm not sure what file is being used to display the above site since there is only one index.php file in my htdocs (and it has the photo).

**Comment by susanBuck** [comment]
Hi @jeremiahazurin - When I just loaded your production site - the "View source" shows it's still loading the code where the image path is missing the closing quote:

![image](https://user-images.githubusercontent.com/237711/65003490-b5fea700-d8c6-11e9-9ddb-b12e7dc5ba6b.png)

Have you pulled the recent changes to production after you fixed it locally (ref #14)?

**Comment by jeremiahazurin** [comment]
I haven't so that's probably the problem. I'm confused as to how to get to production (after I fixed it locally). I'm getting confused with all of the folders and commands but I think my problem is that I'm working in the wrong server/folder/production

**Comment by jeremiahazurin** [comment]
ok so i found _where_ i have to be (i think) but now i encountered another issue where i'm assuming my local file hasn't synced with a server file? 
<img width="729" alt="Screen Shot 2019-09-16 at 21 57 52" src="https://user-images.githubusercontent.com/16971379/65005241-36280b00-d8cd-11e9-9b9e-d9a0a88e27ac.png">

**Comment by jeremiahazurin** [comment]
<img width="729" alt="Screen Shot 2019-09-16 at 22 06 05" src="https://user-images.githubusercontent.com/16971379/65005548-3543a900-d8ce-11e9-95de-6bb549f24996.png">
So I think that I updated/merged everything but my site is still not showing the photo. What am I doing wrong? @susanBuck

**Comment by jeremiahazurin** [comment]
!!! nevermind, i got it! thank you!!
![Screen Shot 2019-09-16 at 22 40 32](https://user-images.githubusercontent.com/16971379/65007113-1dbaef00-d8d3-11e9-9822-b569ab811f27.png)
