### ISSUE TITLE
Cloning Repo: Permission Denied

### ISSUE THREAD

**Issue by chantelledmello** [susanBuck/e2-fall19#19]
Hi guys/prof

I have a very strange error that comes up when I try to clone a repo on my local server. 

I followed all the steps outlined in the notes with setting up the SSH key and testing it (it worked!). I then set up my [E2 repository](https://github.com/chantelledmello/e2) after which I set about cloning the repo. I navigated into the requisite htdocs docs folder and ran the command: 

```php
$ git clone git@github.com:chantelledmello/e2.git
```

That in turn gave me this grave-looking error: 

```php
fatal: could not create work tree dir 'e2': Permission denied
```
Not sure what I'm doing wrong but any help rectifying this ASAP would be much appreciated as this is stalling my progress on Project 1. 

**UPDATE**: I tried running the command with admin privileges (this is my computer and I'm the admin, so wasn't sure if there was something going wrong here) as such:
```php
$ sudo git clone git@github.com:chantelledmello/e2.git
```
to which I then got the following error(s):

```php
Cloning into 'e2'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I also looked up what a 'Permission denied (publickey)' error was and double checked that I had indeed set up my SSH key right by running the command 
```php
$ ssh -T git@github.com
```
To which I got the below confirmation: 
```php
Hi chantelledmello! You've successfully authenticated, but GitHub does not provide shell access.
```

**Comment by susanBuck** [comment]
Hi @chantelledmello 

Can you run the following 4 commands, in order, and copy/paste the **complete output** from your command line program? 

Command 1:
If on Mac:
```
cd /Applications/XAMPP/xamppfiles/htdocs
```

If on Windows:
```
 c:\xampp\htdocs
```


Remaining 3 commands are the same regardless of Mac/Win:
```
ls -la
```

Then:
```
ssh -T git@github.com
```

Then:
```
git clone git@github.com:chantelledmello/e2.git
```

Here's an example of the kind of output I'm expecting (your actual output may vary). Note how I've included the commands and the output.

```
/Applications/XAMPP/xamppfiles/htdocs   $ cd /Applications/XAMPP/xamppfiles/htdocs
/Applications/XAMPP/xamppfiles/htdocs   $ ls -la
total 104
drwxrwxr-x  12 root    admin     384 Sep 10 14:30 .
drwxrwxr-x  34 root    admin    1088 Sep  3 16:13 ..
-rw-r--r--@  1 Susan   admin    6148 Sep 16 19:31 .DS_Store
-rw-rw-r--   1 root    admin    3607 Feb 27  2017 applications.html
-rw-rw-r--   1 root    admin     177 Feb 27  2017 bitnami.css
drwxrwxr-x  28 root    admin     896 Sep  3 16:13 dashboard
drwxr-xr-x   6 Susan   admin     192 Sep 17 13:03 e2
drwxr-xr-x   7 Susan   admin     224 Sep 12 11:36 e28
-rw-rw-r--   1 root    admin   30894 May 11  2007 favicon.ico
drwxrwxr-x   4 root    admin     128 Sep  3 16:13 img
-rw-r--r--@  1 Susan   admin     195 Sep 10 12:41 index.php
drwxrwxr-x   2 daemon  daemon     64 Sep  3 16:12 webalizer
/Applications/XAMPP/xamppfiles/htdocs   $ ssh -T git@github.com
Hi susanBuck! You've successfully authenticated, but GitHub does not provide shell access.
/Applications/XAMPP/xamppfiles/htdocs   $ git clone git@github.com:chantelledmello/e2.git
Cloning into 'e2'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (3/3), done.
Checking connectivity... done.
```

**Comment by chantelledmello** [comment]
Hi Prof, 

See below:

```php
~   $ cd /Applications/XAMPP/xamppfiles/htdocs
/Applications/XAMPP/xamppfiles/htdocs   $ ls -la
total 88
drwxr-xr-x   9 root    admin     306 Sep 17 13:55 .
drwxrwxr-x  40 root    admin    1360 Sep 17 13:16 ..
-rw-r--r--   1 root    admin    3607 Feb 27  2017 applications.html
-rw-r--r--   1 root    admin     177 Feb 27  2017 bitnami.css
drwxr-xr-x  28 root    admin     952 Sep 13 12:25 dashboard
-rw-r--r--   1 root    admin   30894 May 11  2007 favicon.ico
drwxr-xr-x   4 root    admin     136 Sep 13 12:25 img
-rw-r--r--   1 root    admin     197 Sep 17 13:18 index.php
drwxr-xr-x   2 daemon  daemon     68 Sep 13 12:25 webalizer
t@github.coms/XAMPP/xamppfiles/htdocs   $ ssh -T gi 
Hi chantelledmello! You've successfully authenticated, but GitHub does not provide shell access.
/Applications/XAMPP/xamppfiles/htdocs   $ git clone git@github.com:chantelledmello/e2.git
fatal: could not create work tree dir 'e2': Permission denied
/Applications/XAMPP/xamppfiles/htdocs   $ 
```

**Comment by susanBuck** [comment]
Great, thanks! Seeing all the commands in order/context just helps make sure none of our wires are getting crossed.

From your results, it appears your SSH key connection to Github is healthy, but there's a permissions problem with trying to clone into the htdocs directory. This means the user you're operating as does not have write permissions to the htdocs directory.

Let's troubleshoot this...

From your output, we can see all the files/dirs in htdocs that were created as part of the XAMPP install are owned by the user `root` and the group `admin`. 

Now let's compare that to my output --

All my original XAMPP files are also owned by `root/admin`.
And any new files/dirs I've added since installation (e.g. `e2` or `index.php`) are owned by `Susan/admin`.

As the user `Susan` I was able to add new files to the htdocs directory that was owned by `root/admin` because I'm part of the `admin` group.

As evidence of this, I first ran the `whoami` command to confirm who I'm operating as (`Susan`), then I ran the command `groups` and confirmed I see `admin` as one of the listed groups.

```bash
/Applications/XAMPP/xamppfiles/htdocs   $ whoami
Susan
/Applications/XAMPP/xamppfiles/htdocs   $ groups
staff everyone localaccounts _appserverusr admin _appserveradm _lpadmin piavpn _appstore _lpoperator _developer _analyticsusers com.apple.access_ftp com.apple.access_screensharing com.apple.access_ssh
```

Can you do the same thing on your end - `whoami` to confirm which user you are, and `groups` to see what groups you're a part of?

**Comment by chantelledmello** [comment]
Hi @susanBuck,

I noticed the different owners when I was perusing your demo output. I ran the `whoami` and `groups` commands and got the following output:

```php
/Applications/XAMPP/xamppfiles/htdocs   $ whoami
chantelledmello
/Applications/XAMPP/xamppfiles/htdocs   $ groups
staff com.apple.sharepoint.group.1 everyone localaccounts _appserverusr admin _appserveradm _lpadmin _appstore _lpoperator _developer com.apple.access_ftp com.apple.access_screensharing com.apple.access_ssh
```

**Comment by susanBuck** [comment]
Now that we see your user `chantelledmello` is part of the `admin` group, we need to drill deeper to understand why you can't write to it (which is effectively what cloning is attempting to do).

To do this, let's compare the permissions on the htdocs directory itself, which is indicated by the first line output from the `ls -la` command (the one with the period `.`)

Mine:
```
drwxrwxr-x  12 root    admin     384 Sep 10 14:30 .
```

Yours:
```
drwxr-xr-x   9 root    admin     306 Sep 17 13:55 .
```


Permission strings like `drwxrwxr-x` are read like this:

![image](https://user-images.githubusercontent.com/237711/65069047-e04c7500-d957-11e9-8aa5-da47fc16c4f8.png)

Following this pattern, let's read my permission string first (I've added spaces to make it easier to read):
```
d rwx rwx r-x
```
+ d = it's a directory
+ rwx = User can can ead, write, execute
+ rwx = Group can read, write, execute
+ r-x = Other (everyone else) can read and execute, but not write

Now yours:
```
d rwx r-x r-x
```
+ d = it's a directory
+ rwx = User can can ead, write, execute
+ **r-x = Group can read and execute, but not write**
+ r-x = Other (everyone else) can read and execute, but not write

The key problem here is the group `admin` for which you (`chantelledmello`) is a part of, can read and execute, but **it can't write to that directory**.

To fix this, try this command:
```
chmod -r g+w /Applications/XAMPP/xamppfiles/htdocs
```

Explanation:
+ The `chmod` command is used to adjust permissions
+ The `-R` says to make the change recursively - i.e. for the directory and all of its contents
+ The `g` says we're changing the group permission
+ The `+w` says we're adding write permissions

After you run the above command the permissions of your htdocs folder should look like mine (`drwxrwxr-x`) and you *should* be able to clone into it. Knock on wood. : )

**Comment by chantelledmello** [comment]
Hi @susanBuck,

Thanks for explaining that so clearly! I tried to run the command you seggested that but it gave me the following error message 🙈

```
 $ chmod -r g+w /Applications/XAMPP/xamppfiles/htdocs
chmod: g+w: No such file or directory
chmod: Unable to change file mode on /Applications/XAMPP/xamppfiles/htdocs: Operation not permitted
/   $ 
```

So then I tried the more direct/front-end approach of right-clicking on the htdocs folder, opening the Sharing and Permissions part of the info window and then manually setting the admin access from Read only to Read and write....WHICH WORKED!

I then ran the git clone command, got the success message, and now have a shiny new E2 folder in my htdocs file. 

I'd still definitely like to understand how I could have done the same via the command line, so any light you can shed on that would be much appreciated!

**Comment by susanBuck** [comment]
Ah, the command didn't work because of a silly typo on my part! The -r should have been capitalized:

```
chmod -r g+w /Applications/XAMPP/xamppfiles/htdocs
```

I'm glad you found an alternative solution and the problem's solved!

**Comment by chantelledmello** [comment]
Ah! Gotcha @susanBuck! 

Thanks for all your help 😁
