### ISSUE TITLE
Localhost Access denied: Error 403

### ISSUE THREAD

**Issue by chantelledmello** [susanBuck/e2-fall19#20]
Hi @susanBuck!

Back again with another issue. This time, it has to do with an error in accessing my localhost entirely. This was working just fine until I followed the steps outlined in the video and notes to create my local domain (practice.loc). 

I changed all the requisite files and added the necessary lines of code, but when I try to type in 'localhost' as my URL, it comes up with this error:

<img width="1438" alt="Screen Shot 2019-09-17 at 7 07 36 PM" src="https://user-images.githubusercontent.com/26146422/65086063-71cedd80-d97e-11e9-90da-6b99373aed31.png">

My practice.loc domain however, works just fine, as below:

<img width="1440" alt="Screen Shot 2019-09-17 at 7 07 50 PM" src="https://user-images.githubusercontent.com/26146422/65086079-7c897280-d97e-11e9-8ef9-7568708e8ac9.png">

**Comment by chantelledmello** [comment]
UPDATE: 

I solved it by opening my httpd.vhosts.conf file and adding the following Virtual Host as my default/localhost

```
# localhost
<VirtualHost *:80>
    ServerName localhost
    DocumentRoot "/Applications/XAMPP/xamppfiles/htdocs"
    <Directory "/Applications/XAMPP/xamppfiles/htdocs">
        Options Indexes FollowSymLinks Includes execCGI
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
```

**Comment by susanBuck** [comment]
Glad you got it sorted out @chantelledmello! 

For reference for other students reading this/facing a similar problem, there's a section in the notes about this: [Local domains: Fixing http://localhost](https://hesweb.dev/e2/notes#/local-server/local-domains?jump=fixing-codehttplocalhostcode)
