### ISSUE TITLE
prod server error NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by baugh20s** [susanBuck/e2-fall19#21]
When I attempt to go to my domain, baugh20s.me, I get the error 

> Your connection is not private.

(Screenshot of full message attached). I've had this domain through Namecheap since last fall for another PHP course. It was set to expire soon (9/20) but had not yet.

I've attached a screenshot of the error message, the DNS records, and my virtual host setting. I think these are correct so I'm not sure how to move forward with troubleshooting.

![prod error](https://user-images.githubusercontent.com/20144373/65088376-1f45ef00-d987-11e9-9489-b8f86d4d7711.png)

![virtual hosts](https://user-images.githubusercontent.com/20144373/65088380-24a33980-d987-11e9-8799-445cdb244e2f.png)

![dns records](https://user-images.githubusercontent.com/20144373/65088377-21a84900-d987-11e9-8ded-858ee99bc9b1.png)

**Comment by susanBuck** [comment]
It looks like all traffic to `http://baugh20s.me` is forwarding to `https://baugh20s.me` (that's http followed by an `s` for secure), and there's not a SSL certificate set up on the server, resulting in the message the browser is showing you.

Are you using a new DigitalOcean server/droplet, or one from a previous semester?

If the latter, is there any chance you had set up https on that server?

**Comment by baugh20s** [comment]
It's a new one.

**Comment by susanBuck** [comment]
Ok - 

I see from your screenshot that your domain is configured to point to the IP address `104.248.122.90`.

When I visit <http://104.248.122.90> I would expect to see the content from your DigitalOcean server, but instead I see this:

![image](https://user-images.githubusercontent.com/237711/65088979-5b7a4f00-d989-11e9-8724-364ba6f82285.png)

Contrast this to when we go to the IP for my DigitalOcean server (http://http://165.22.189.157/):
![image](https://user-images.githubusercontent.com/237711/65089010-82388580-d989-11e9-9875-6b5af3154f20.png)


Can you confirm `104.248.122.90` is the correct IP address of your DigitalOcean server?

**Comment by baugh20s** [comment]
This seems very obvious now - thank you. I must have pasted in some other IP address. The correct one is 68.183.154.92.

**Comment by susanBuck** [comment]
no problem - sometimes it just takes a fresh set of eyes. : )
