### ISSUE TITLE
FYI: Week 1 assignment grades released; HTML code question dropped

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall19#24]
Hi everyone,

I just released the Week 1 assignment grades in Canvas. You should have received a notification from Canvas, and you should be able to go in to see what you missed, the correct answers, as well as any feedback I might have left. 

FYI that I effectively dropped question 14 by awarding everyone full credit for it, regardless of your answer.

![image](https://user-images.githubusercontent.com/237711/65195122-e459bf00-da4b-11e9-973c-13280a8a8a47.png)

I did this because there was inconsistency in how Canvas was showing me your answers - for some I saw the raw HTML (what I wanted), for others, I saw a rendered list (which left me no way to actually see the HTML).

So if you're curious, and so you can compare it to what you entered, here's the rough idea of the answer I was expecting for this question:

```html
<ol>
    <li><a href='http://path-to-amazon/book1'>Book 1</a></li>
    <li><a href='http://path-to-amazon/book2'>Book 2</a></li>
    <li><a href='http://path-to-amazon/book3'>Book 3</a></li>
</ol>
```

**If you have questions about your grade/assignment, please don't post it here publicly. Instead, email me directly at susanbuck@fas.harvard.edu.**

**Comment by janenycxo** [comment]
Thanks for the heads up!
