### ISSUE TITLE
Localhost  Is Not Working After Week 2 Changes

### ISSUE THREAD

**Issue by Matt49** [susanBuck/e2-fall19#25]
After making the suggested modifications to set up our local domains my localhost address, `http://localhost`, gives me the following error message

>Access forbidden!

>You don't have permissions to access the requested directory. There is either no index document or the directory is read protected.

>Error 403

The subdomains we set up work just fine. I'm wondering if localhost not working is par for the course or if I'm missing something in my local set up.

The line we modified in our XAMPP **httpd.conf** file looks like this:

```
# Virtual hosts
Include etc/extra/httpd-vhosts.conf
```

My XAMPP **httpd-vhosts.conf** file looks like this:

```
<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host.example.com
    DocumentRoot "/Applications/XAMPP/xamppfiles/docs/dummy-host.example.com"
    ServerName dummy-host.example.com
    ServerAlias www.dummy-host.example.com
    ErrorLog "logs/dummy-host.example.com-error_log"
    CustomLog "logs/dummy-host.example.com-access_log" common
</VirtualHost>

<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host2.example.com
    DocumentRoot "/Applications/XAMPP/xamppfiles/docs/dummy-host2.example.com"
    ServerName dummy-host2.example.com
    ErrorLog "logs/dummy-host2.example.com-error_log"
    CustomLog "logs/dummy-host2.example.com-access_log" common
</VirtualHost>

<VirtualHost *:80>
    ServerName practice.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e2/practice
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e2/practice>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName p1.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e2/p1
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e2/p1>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
    </Directory>
</VirtualHost>
```

My computer's **host file** looks like this:

```
127.0.0.1               localhost
255.255.255.255         broadcasthost
127.0.0.1 practice.loc
127.0.0.1 p1.loc
```
Previously the host file  contained the line below, which I erased because I thought it looked odd. Localhost did not work with this line included either.

```
::1                          localhost
```

*Thank you for the help.*

**Comment by susanBuck** [comment]
Hi @Matt49 -

There's a part near the bottom of the Local Domain notes that explains how to fix that:
[Fixing http://localhost](https://hesweb.dev/e2/notes#/local-server/local-domains?jump=fixing-codehttplocalhostcode)

Check that out and let us know if you have any follow-up questions.

**Comment by RGPhD** [comment]
Hello @Matt49 ,
I am sure you probably did this, but remember to *restart* your server. 
Robelyn

**Comment by Matt49** [comment]
Thanks @susanBuck and @RGPhD 

That did it. I just need to read further down the page. Sorry about that.
