### ISSUE TITLE
embeded PHP tags and tidy html

### ISSUE THREAD

**Issue by philyuska** [susanBuck/e2-fall19#27]
When i embed PHP tags in the HTML, there are some unwanted white space characters being embedded as well.  Am i missing something here or is there a best practice to follow?

for example
this snippet of code:
```
		<h2>Tidier Code</h2>
		<ul>
		<?php foreach ( $cards as $rank => $card ) { ?>
			<li>Card is <?php echo "$card"; ?> Rank is : <?php echo "$rank"; ?></li>
		<?php } ?>
		</ul>
```
yields this when i view source in my browser:
>		<h2>Tidier Code</h2>
>		<ul>
>					<li>Card is A Rank is : 1</li>
>					<li>Card is 2 Rank is : 2</li>
>					<li>Card is 3 Rank is : 3</li>
>				</ul>

while this snippet of code:
```
		<h2>Tidier HTML</h2>	
		<ul>
		<?php foreach ( $cards as $rank => $card ) { ?>
	<li>Card is <?php echo "$card"; ?> Rank is : <?php echo "$rank"; ?></li>
		<?php } ?>
</ul>
```
yields this when i view source in my browser:
>		<h2>Tidier HTML</h2>	
>		<ul>
>			<li>Card is A Rank is : 1</li>
>			<li>Card is 2 Rank is : 2</li>
>			<li>Card is 3 Rank is : 3</li>
>		</ul>

**Comment by susanBuck** [comment]
@philyuska It's common/expected that the *View Source* version of the HTML will not be perfectly tidy once the PHP is rendered.

The important thing is that it's tidy in your editor when you're working with the code.

And note - when grading - I always look at the code in your repository, I never grade off of *View Source*.
