### ISSUE TITLE
VSC with XAMPP - does it require git?

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e2-fall19#29]
After I opened the XAMPP http - e2 folder in VSC, I got the message "git is not installed".  
Do I need to enable git in VSC? Would there be any conflict with the CL?_

**Comment by susanBuck** [comment]
Hi @anyav77 -

It could be that VSCode can't find your install of git.

In command line, the following command can tell you the path to your Git install:

Mac:
```
which git
```

Windows
```
where.exe git
```

Once you know that, you can tell VSCode the path via your settings:

![image](https://user-images.githubusercontent.com/237711/65373870-1425e400-dc51-11e9-917d-9bed5ecdd375.png)

Note for anyone else reading this thread: Using git via VSCode isn't required.

**Comment by anyav77** [comment]
The git installation path is:

`λ where.exe git
C:\cmder-master\vendor\git-for-windows\cmd\git.exe
C:\cmder-master\vendor\git-for-windows\mingw64\bin\git.exe`

What is the proper way to define it in the settings?  Should I copy the paths as they are, or modify the code?
`{
    "editor.lineHeight": 0,
    "editor.fontSize": 18,
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Pop N' Lock Theme by Luxcium ✨",
    "editor.minimap.enabled": false,
    "editor.formatOnSave": true,
    C:\cmder-master\vendor\git-for-windows\cmd\git.exe
    C:\cmder-master\vendor\git-for-windows\mingw64\bin\git.exe

}`

**Comment by susanBuck** [comment]
Hi @anyav77 - Here's the syntax you're looking for:

```
{
    // Is git enabled
    "git.enabled": true,

    // Path to the git executable
    "git.path": "C:\\path\\to\\git.exe"

    // other settings
}
```

Notes:
+ VSCode restart required after making this setting change. 
+ You only have to specify a path to one of your git installs. `C:\cmder-master\vendor\git-for-windows\cmd\git.exe` should be fine.

Ref: <https://stackoverflow.com/a/33946918/59479>

If that doesn't do the trick, let us know!

**Comment by susanBuck** [comment]
^^^ Didn't mean to close this post just now. Will keep this open until you confirm it's working.

**Comment by shcantrell** [comment]
I have been getting that message in VSCode, as well. I have been ignoring it because it has not caused me any issues. Should I address it, after all? 

<img width="342" alt="Git_not_Found" src="https://user-images.githubusercontent.com/50802945/65470762-97eef480-de3a-11e9-972f-ceb4fcd499c4.PNG">

**Comment by susanBuck** [comment]
Not necessary to address it since we're not using git via VSCode in in this course. Everything git related we manage from command line.

Only address it if you're interested in checking out VSCode's version control functionality.

Otherwise, click *"Don't Show Again"* so the message won't keep popping up.

**Comment by AntonieKowal** [comment]
I added the two lines to my settings.json file and am not getting any errors, but my VSCode still can't find the git.exe, though I'm no longer prompted to download git like the above image. I've restarted a few times as well, and navigated through the path manually in my documents to make sure it was there. Did I write the path in incorrectly? Thanks!

![githelp](https://user-images.githubusercontent.com/47436865/65551011-e1991700-deee-11e9-8920-820096b23799.png)

**Comment by anyav77** [comment]
I tried adding the code and restarting git, but now I'm getting an error:
> Invalid escape character in string

![VSCode error](https://user-images.githubusercontent.com/1045307/65562480-786bd080-defb-11e9-937e-6ecc23fd08cd.png)

**Comment by AntonieKowal** [comment]
It seems that you need to put two slashes between every directory in the path, because it's misinterpreting \c, \g, and \v as something separate from what we're trying to achieve..

```
// Path to the git executable
"git.path": "C:\\path\\to\\git.exe"
```

It seems that this should be acceptable syntax that will get rid of the error, but mine still doesn't work so I might be wrong!

**Comment by anyav77** [comment]
Thanks!  It helped to remove the error.
