### ISSUE TITLE
Question About Item 1 of First Quiz

### ISSUE THREAD

**Issue by MPVaccaro** [susanBuck/e2-fall19#3]
## Question 1 of First Quiz

We are using an HTML/WISIWIG editor in our quiz.  When I'm writing **Markdown** it shows the code, not the **_result_**.  

Is this what is expected, or am I missing something?

**Comment by philyuska** [comment]
> ## Question 1 of First Quiz
> We are using an HTML/WISIWIG editor in our quiz. When I'm writing **Markdown** it shows the code, not the **_result_**.
> 
> Is this what is expected, or am I missing something?

For the answers to the __Markdown__ questions I just pasted the `text` from the `Write` window into __Canvas__.

**Comment by janenycxo** [comment]
I included the markdown, HTML, and output to cover all my bases. Perhaps the html would have been sufficient. Any pointers?

**Comment by RGPhD** [comment]
Dear @MPVaccaro,
You can test your **Markdown** in GitHub and then enter the exact code in Canvas.
Robelyn

**Comment by janenycxo** [comment]
The professor posted this link to a markdown editor (with a live preview) you might also find helpful: https://dillinger.io/

**Comment by susanBuck** [comment]
Sorry I'm late to this thread - thought I had replied the other day.

For that question I was expecting the raw Markdown. I don't need to see what it renders as - I just want to confirm you're comfortable writing Markdown.
