### ISSUE TITLE
Acceptable Game Concept?

### ISSUE THREAD

**Issue by shcantrell** [susanBuck/e2-fall19#30]
Hello @susanBuck 

I wanted to bounce off my game concept to make sure it was acceptable. I think this problem is at a beginner/intermediate level to solve. Let me know, otherwise. Thank you.

# Primary & Secondary Colors

**Mechanics**
* An initial random selection is made from three primary colors: red, blue, or yellow.
* A second random selection is made from three primary colors: red, blue, or yellow.
* Selections resulting in one red and one blue color outputs a secondary color of purple.
* Selections resulting in one red and one yellow color outputs a secondary color of orange.
* Selections resulting in one blue and one yellow color outputs a secondary color of green.
* Selections resulting in the same color will not be calculated as part of the output result (?)

**Results**
* Conduct 50 rounds of draws.
* State which secondary color has the most output and its quantity.
* State how often same colors were selected (?) per color (?) - maybe?

**Comment by susanBuck** [comment]
This is a great idea and very appropriate for the scope/scale of the project. 👍

**Comment by shcantrell** [comment]
@susanBuck  - okay, great. Thank you.
