### ISSUE TITLE
Loop outputs only one item to index.php

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e2-fall19#32]
I'm trying to output each iteration of the "for loop" into index.php.  

```php    
    <?php for ($i = 0; $i < 5; $i++) { ?>
        <li>The winner is <?php echo $winner; ?></li>
    <?php } ?>
```

However, it outputs the last iteration 5 times, instead of outputting each iteration:
![loop issue](https://user-images.githubusercontent.com/1045307/65913756-44722e80-e385-11e9-9e9d-d1718414d536.png)

[http://p2.atozez.com/](http://p2.atozez.com/
)

Here is the code in the controller:
```php
for($i = 0; $i < 5; $i++) {
    $player1Move = $moves[rand(0, 2)];
    $player2Move = $moves[rand(0, 2)];
    var_dump($player1Move);
    var_dump($player2Move);

    if($player1Move == $player2Move){
        var_dump('Tie');
        $winner = "Tie";
    }elseif(($player1Move == "rock" and $player2Move == "scissors") || ($player1Move == "paper" and $player2Move == "rock") || ($player1Move == "scissors" and $player2Move == "paper")) {
        var_dump('Player A wins');
        $winner = "Player A";
    } else{
        var_dump('Player B wins');
        $winner = "Player B";
    }
}
```

**Comment by susanBuck** [comment]
In your for loop, you need to track the game play somehow.

For example, you could have a `$results` array, and for each round the results are appended to that array.

Then, in your view, you could iterate through and display the results:
```html
<ul>
    <?php foreach($results as $key => $result) { ?>
        <li><?php echo $result; ?></li>
    <?php } ?>
</ul>
```

**Comment by anyav77** [comment]
Thank you!  I was able to output the results for each round using this method:
[http://p2.atozez.com/](http://p2.atozez.com/)

I also am trying to specify the player moves using a multi-dimensional array:

```php
$results = [
    'player1' => [1],
    'player2' => [2],
    'winner' => [3],
];
```
However, I'm unable to pull the nested array results into the index.php loop list:

> Notice: Array to string conversion in C:\xampp\htdocs\e2\p2\index.php on line 32
> Array

```php
$results = [
    'player1' => ["rock", "paper", "scissors", "rock", "rock"],
    'player2' => ["paper", "rock", "scissors", "rock", "rock"],
    'winner' => ["player B", "test", "test", "test", "player A"],
];
```

> Player A chooses
> Notice: Array to string conversion in C:\xampp\htdocs\e2\p2\index.php on line 30
> Array
> Player B chooses
> Notice: Array to string conversion in C:\xampp\htdocs\e2\p2\index.php on line 31
> Array
> The winner is
> Notice: Array to string conversion in C:\xampp\htdocs\e2\p2\index.php on line 32
> Array

**Comment by anyav77** [comment]
I got rid of the error and make it partially work:

Index-controller:
`php
$result = [
    'player1' => ["rock", "paper", "scissors", "rock", "rock"],
    'player2' => ["paper", "rock", "scissors", "rock", "rock"],
    'winner' => ["player B", "test", "test", "test", "player C"],
];
`
index.php
```html
    <ul>
    <?php foreach($result as $key) { 
            foreach($key as $key => $val){
            
        ?>
        <li><?php echo $key ?></li>
        <li><?php echo $val ?></li>

        <!-- <li>Player A chooses <?php echo $key['player1']; ?></li>
        <li>Player B chooses <?php echo $key['player2']; ?></li>
        <li type = none>The winner is <?php echo $result['winner']; ?><br><br></li> -->
    <?php }} ?>
    </ul>
```
However, it outputs all the values sequentially.  How do I forse it to output the first one for each array, then the second one for each array, etc?

**Comment by susanBuck** [comment]
I suggest organizing your `$results` array. 

Instead of organizing it by the data points (all player1 moves, all player2 moves, all winner results), organize it by the rounds.

Example:
```php
<?php
# Each element in this array represents a single round
# For each round we have the player1 move, the player2 move, and the `winner` results
$results = [
    ['player1' => 'rock', 'player2' => 'paper', 'winner' => 'Player B'],
    ['player1' => 'paper', 'player2' => 'rock', 'winner' => 'Player A'],
    ['player1' => 'scissors', 'player2' => 'scissors', 'winner' => 'Tie']
];
```

Then your foreach loop to display is more straightforward, and does not require any nested loops:

```html
<?php foreach ($results as $roundNumber => $round) { ?>
<ul>
    <li>Round number: <?php echo $roundNumber; ?>
    <li>Player 1: <?php echo $round['player1']; ?>
    <li>Player 2: <?php echo $round['player2']; ?>
    <li>Winner: <?php echo $round['winner']; ?>
</ul>
<?php }
```

**Comment by susanBuck** [comment]
Closing this thread due to inactivity, but feel free to re-open or start a new thread is this question is still pending.
