### ISSUE TITLE
VSC message: can't validate because no php executable is set

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e2-fall19#37]
After attempting to save a workspace in Visual Studio Code, I got this message:

> Cannot validate since no PHP executable is set. Use the setting 'php.validate.executablePath' to configure the PHP executable.

See attached.  
![php executable error](https://user-images.githubusercontent.com/1045307/66689442-b4af6880-ec3f-11e9-9748-f40314b14b1a.png)

On a different note, I noticed that the files/folders are color coded: green, orange, grey.
Green files are labeled as Untracked.  Is it related to this issue?

**Comment by susanBuck** [comment]
To resolve this warning you should set the PHP executable path in your settings. This tells VSCode where to find your PHP install.

You'll do this in your VSCode `settings.json` file located at:

```
C:\Users\YourUsername\AppData\Roaming\Code\User\settings.json
```

The line you want to add is:

```json
"php.validate.executablePath": "c:\\xampp\\php\\php.exe"
```

If that doesn't clear things up, let us know!

The colors you're seeing on the file names are related to version control/git, and shouldn't be related.

**Comment by anyav77** [comment]
Thank you!  I added the line, and I don't see the error anymore.
