### ISSUE TITLE
p2 subdirectories not working

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e2-fall19#38]
I have two subdirectories in p2:
"prev" [http://p2.atozez.com/prev/](http://p2.atozez.com/prev/)
and "rev" (local only at the moment)

None are working at the moment. On the local server, prev and rev result in PHP errors:

```
Warning: require(index-controller.php): failed to open stream: No such file or directory in C:\xampp\htdocs\e2\p2\prev\index.php on line 1

Fatal error: require(): Failed opening required 'index-controller.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\e2\p2\prev\index.php on line 1
```

On the remote server, I get 500 error. The file was working before, and nothing has changed.

**Comment by anyav77** [comment]
I also noticed a message in XAMPP:

> 4:56:20 PM  [main] 	You are not running with administrator rights! This will work for
> 4:56:20 PM  [main] 	most application stuff but whenever you do something with services
> 4:56:20 PM  [main] 	there will be a security dialogue or things will break! So think 
> 4:56:20 PM  [main] 	about running this application with administrator rights!

I'm referencing it, in case it may be related.

**Comment by RGPhD** [comment]
Hi @anyav77,

I created subdirectories for my practice domain and I received the first **Warning** message you received.  My mistake was having the files in the incorrect folder; I had the files in the e2 folder.  I moved all of my files to the practice folder (inside the e2 folder) on my local server, git pushed them to Github and then git pulled them to Digital Ocean and I can now see them in my practice folder and on my practice subdomain.  I did the same with extra p3 files and pages that I added <http://p3.robelyngarcia.me/wbatrivia.php>.

I did not receive the second XAMPP messages you received; my <http://practice.robelyngarcia.me/bank.php> and
<http://practice.robelyngarcia.me/p3game> started working after I moved all of the files to the practice folder.

I might mention that with my Digital Ocean subdomains, they only work without the `www` protocol identifier and only with `http` protocol.  I am not sure if this will help; this is all I think of right now that may be causing your issue.

Robelyn

**Comment by susanBuck** [comment]
I think it's a typo issue.

Your include line looks like this:

```
<?php require "index-controller.php"?>
```

But your controller file name is [index_controller.php](https://github.com/anyav77/e2/blob/master/p2/prev/index_controller.php) (underscore instead of hyphen).

**Comment by janenycxo** [comment]
HI @anyav77 
Were you able to resolve by moving the files as @RGPhD described? or was it the typo?
Jane

**Comment by anyav77** [comment]
Yes, it was a typo in the file name.  Thank you so much!
