### ISSUE TITLE
Rock, Paper, Scissors: Multiple Rounds 

### ISSUE THREAD

**Issue by Matt49** [susanBuck/e2-fall19#43]
Hi All,

I've hit a road block with my p3 and am spinning my wheels...

I appreciate any hints that might help me get unstuck.

I'm building *Rock, Paper, and Scisors*. I have one round of it working but would like to make it so that the player or the computer must win two out of three rounds in order to win.

I'm not sure how to store the player scores from round to round. They get erased when the variable is declared again. 

**My Plan**

1) Create a variable for both player points and one for computer points.
2) Add to each of the variables when that player wins.
4) Use "if statements" saying if one of the player's sum equals the numbr 2, send a message saying that player won the game and also clear both "player point" variables.

An Idea I'v tried and failed at is using a session to somehow store the previous round score.

I'm also wondering if there is a way to use a conditional with isset in which I could put the "player point" variable declaration. That way it is not reset.

**Process.php**

```
<?php

session_start();


//Throw options
$throws = ['rock', 'paper', 'scissors'];

//Player's Choice
$playerThrow = $_GET['throw'];


$compThrow = $throws[rand(0,2)];

//Comparison result variable
$playerResult = null;



//Conditional statements to compare throws accoring to game rules
if ($playerThrow == $compThrow) {
    $playerResult = 'tie'; 
} elseif ($playerThrow == 'rock' and $compThrow == 'paper') {
    $playerResult = 'lose';
} elseif ($playerThrow == 'rock' and $compThrow == 'scissors') {
    $playerResult = 'win';
} elseif ($playerThrow == 'paper' and $compThrow == 'rock') {
    $playerResult = 'win';
} elseif ($playerThrow == 'paper' and $compThrow == 'scissors') {
    $playerResult = 'lose';
} elseif ($playerThrow == 'scissors' and $compThrow == 'paper') {
    $playerResult = 'win';
} else {
    $playerResult = 'lose';
} 

$playerPoints = null;
$compPoints = null;

if ($playerResult == 'win') {
    $playerPoints = $playerPoints + 1; 
}

if ($playerResult == 'lose') {
    $compPoints = $playerPoints + 1; 
}

$outcome = [
    'outcome' => $playerResult,
    'computer' => $compThrow,
    'player' => $playerThrow,
    'points' => $playerPoints,
    'compPoints' => $compPoints,
];

$_SESSION['outcome'] = $outcome;   


header('Location: index.php');

```

**Comment by Matt49** [comment]
I've posted my latest attempt at getting rounds to work to my github here. I'm trying to use sessions to preserve the data between rounds. This iteration is just trying to preserve a score for the player based on whether he wins or not.

https://github.com/Matt49/e2/tree/4ccd6ef62bbc5564f7a99e40142e06e13c779f1f/p3

**Comment by shcantrell** [comment]
@Matt49

Did it work? I cannot tell. This one is challenging for me, as well. 

I am making some wild guess here...

In the form flow lecture video, the last example with Design C, Susan showed an issue where the output did not go away after the page was refreshed. It was due to the `isset` function retaining the results; therefore, the variable causing the issue was iterated and equated to `null` to reset the variable. 

Maybe removing the `$_SESSION['outcome'] = null;` from your index-controller.php will retain the results?

Maybe the design flow is the issue? (not sure - just guessing).

**Comment by philyuska** [comment]
Hi Matt,
I think this stanza in process.php maybe re-initializing your `$playerPoints` variable every time there is a post.
```php
if (empty($playerPoints)) {
    $playerPoints = 1;
} else {
    $_SESSION['playerPoints'] = $_POST['playerPoints'];
    $playerPoints = $_SESSION['playerPoints'];
}
```
If you try checking if the session variable exists first and if not initialize it does that get you the desired effect?
Something along the lines of:
```php
if (isset($_SESSION['playerPoints'])) {
	$playerPoints = $_SESSION['playerPoints'];
} else {
	$playerPoints = 1;
}
```



Cheers

**Comment by Matt49** [comment]
Yes! That works. I had been going down a few rabbit holes. One was that I thought I had to pass the $_SESSION to my index.php file and back again. It does makes sense that you don't have to do that.

Thank you for the help!
