### ISSUE TITLE
Unexpected end of file in process

### ISSUE THREAD

**Issue by jeremiahazurin** [susanBuck/e2-fall19#44]
Hi, I'm not sure why my process.php file has an "Unexpected end of file" error. I thought I linked it correctly to my index.php file. I'm following the Design C approach.

https://github.com/jeremiahazurin/e2/blob/master/p3/process.php

**Comment by philyuska** [comment]
looks like you are missing the closing curly bracket in this code block?
```php
if($_GET['p1']){
    $moves = array(Rock, Paper, Scissors);
    $moves = rand(0,2);
    $p1 = $_GET['p1'];
    $p2 = $choose[$moves];
```

Cheers

**Comment by jeremiahazurin** [comment]
Thank you @philyuska! Sharp eyes
