### ISSUE TITLE
[Design C] Index not showing results

### ISSUE THREAD

**Issue by jeremiahazurin** [susanBuck/e2-fall19#45]
My index page is not showing the results. I'm pretty sure that I "linked" everything correctly but I can't seem to find where I went wrong (in either the process or controller file). Am I calling/redirecting the results properly in my [process](https://github.com/jeremiahazurin/e2/blob/master/p3/process.php) file and displaying properly in my [index](https://github.com/jeremiahazurin/e2/blob/master/p3/index.php)? Or am I missing this altogether

`$results = [`
    `'winner' => $winner,`
   ` 'moves' => $moves,`
    `'choice' => $choose,`
`];`

from my index:
`<?php if ($showResults) { ?>`
` P1 chose: <?php echo $results['moves']; ?>`
  `P2 chose: <?php echo $results['choice']; ?>`
 ` }`

  `<?php if ($results['winner']) { ?>`
    `You won`
  `<?php } else {?>`
 `   You lost`
 ` <?php } ?>`
`<?php } ?>`

**Comment by susanBuck** [comment]
In `process.php` you attempt to get the radio button choice using `$_GET['p1']` (this occurs in two places).

But the name on your radio buttons is not `p1`, it's `choice`:

```html
<input type='radio' value='rock' id='rock' name='choice'>
<label for='rock'> Rock </label> <br/>
```

FYI/tip on debugging stuff like this -
At the top of your process.php file I added a `var_dump($_GET)` so I could see the data you were getting from the form. I also temporarily commented out the redirect line (`header('Location: index.php');` so that when I submitted the form I could see the results of the var_dump without it redirecting back to index.php. 

Once I could see the data of the form, I was able to identify the mismatch.

After you fix the above issue, you'll run into another...

Your if/else construct is just echo'ing the results:

```php
if ($p1 == $p2) {
    echo 'Tie';
} elseif ($p1 == 'Rock' and $p2 == 'Scissors') {
    echo 'Win';
etc...
```

Instead of echo'ing results, it should be updating the `$winner` details so it can then be set in the session before the redirect:

```php
$results = [
    'winner' => $winner,
    'moves' => $moves,
    'choice' => $choose,
];

$_SESSION['correct'] = $correct;
header('Location: index.php');
```

If you're still having problems after addressing the above issues, let me know!

**Comment by jeremiahazurin** [comment]
I'm still having trouble. I changed the `p1` to `choice` in `$_GET' and added the `$winner` details, but I'm now getting an error on line 15 of process. All brackets supposed to be closed, right?

**Comment by susanBuck** [comment]
```
Parse error: syntax error, unexpected '}' in process.php on line 15
```

Here's the relevant code:

```php
if($p1 == $p2){
    echo 'Tie';
    $winner = 'There was a tie!'
    } elseif($p1 == 'Rock' and $p2 == 'Scissors'){ # THIS IS LINE 15
    echo 'Win';
    $winner = 'You won!'
    } elseif($p1 == 'Rock' and $p2 == 'Paper'){
    echo 'Lose';
    $winner = 'You lost'
````

Line 15 actually looks ok, so remember the tip about starting on the line where it tells you the error is and then moving up.

In this case, the issue starts on line 14 because `$winner = 'There was a tie!'` does not end in a semi-colon. As a result, once it gets to line 15 and sees the `}` it's unexpected.

Check all the lines where you set the `$winner`, because they're all missing a closing semi-colon.

Once you fix that, you'll get another error:

```
Warning: Use of undefined constant Rock - assumed 'Rock' (this will throw an Error in a future version of PHP) in /Users/Susan/Sites/dwa-bash/students/e2/p3/process.php on line 6
```

This is because of how you defined your `$moves` array:

```php
$moves = array(Rock, Paper, Scissors);
```

Recall that string values should be surrounded in quotes. Without quotes, it sees `Rock`, `Paper`, and `Scissors` as [constants](https://www.php.net/manual/en/language.constants.php) - which are like variables, except they can't change and they aren't prefixed with `$`.

Finally, you still have a line where you're attempting to get `p1` instead of `choice` from the `$_GET` data.

You'll face a couple more bugs/issues after this, but I don't want to give away all the answers, so continue to debug and follow-up as you get stuck.

**Comment by jeremiahazurin** [comment]
Hmm... I can't seem to find solutions after debugging the above. My results still aren't showing in my index file. I feel like it has something to do with this in my process file:

`$results = [`
   ` "winner" => $winner,`
    `"moves" => $moves,`
    `"choice" => $choose,`

and my superglobal:

`if($_GET["choice"]){`
  `  $winner = null;`
    `$moves = array("Rock", "Paper", "Scissors");`
    `$moves = rand(0,2);`
    `$p1 = $_GET["choice"];`
    `$p2 = $choose[$moves];`

So far I've changed around the variables so they're consistent but I'm not seeing the error

**Comment by susanBuck** [comment]
To debug this, try adding a debug statement that outputs the $results array via `var_dump($results)`. 

Also, comment out the redirect line at the end of the file so you'll be able to see the resulting output.

![image](https://user-images.githubusercontent.com/237711/66865792-facd3a80-ef65-11e9-890c-583a9d77bcf4.png)

Doing that will provide insight into what data your process.php file is actually producing. 

In this instance, it will actually reveal that process.php has some errors that need to be sorted out:

![image](https://user-images.githubusercontent.com/237711/66865845-1c2e2680-ef66-11e9-939f-09d4734896d0.png)

**Comment by jeremiahazurin** [comment]
Thank you! That was helpful. But now I'm not understanding why it's printing `array(3) { ["winner"]=> NULL ["moves"]=> int(2) ["choice"]=> NULL }`, or frankly what that even means. I thought it was supposed to have a null statement anyways? Since all "new" games have to start at null?

**Comment by susanBuck** [comment]
`$winner` is initialized as null at the start, yes, but after the if/else constructs it should have had its value set to either "You won", "You lost" or "Tie".

By dumping `$results`, we can see that `$winner` is still null by the end of the file, which means something isn't working right.

Knowing this, we have to look closer at the if/else constructs and figure out **why one of the branches in that construct is not being triggered.**
```php
if ($p1 == $p2) {
    echo("Tie");
    $winner = ("Tie!");
} elseif ($p1 == "Rock" and $p2 == "Scissors") {
    echo("Win");
    $winner = "You won!";
} elseif ($p1 == "Rock" and $p2 == "Paper") {
    echo("Lose");
    $winner = "You lost";
} elseif ($p1 == "Paper" and $p2 == "Rock") {
    echo("Win");
    $winner = "You won!";
} 
// ... etc ...
```

Note how each of your boolean expressions is testing the variables `$p1` and `$p2` - so we want to take a closer look at those variables and make sure they're getting to values we're expecting, e.g. `"Paper"`, or `"Rock"`, or `"Scissors"`.

Again, our friend `var_dump` can help us out here... Let's dump `$p1` and `$p2` in `process.php` to see what value they end up as:

![image](https://user-images.githubusercontent.com/237711/66870745-22c19b80-ef70-11e9-8e5a-5c5d6971477e.png)

When I test that, it gives me this:

![image](https://user-images.githubusercontent.com/237711/66870819-44bb1e00-ef70-11e9-9bc1-72e46e277c31.png)

I see two problems here:

First, `$p1` is set to `rock` - all lowercase. Compare that to your boolean conditionals, e.g. `$p1 == "Rock" and $p2 == "Scissors"`, where you use uppercase. **Make these consistent.**

Second, `$p2` is null. According to your code $p2 should be set to `$moves[rand(0,2)]`.

![image](https://user-images.githubusercontent.com/237711/66870943-8ba91380-ef70-11e9-8e89-ced457a21062.png)

In theory, that should work, assuming `$moves` is an array of values "Rock", "Paper", or "Scissors" - which is what you set it to on line 6. *But*, then on line 7 you're-set `$moves` to something else...

```php
$moves = rand(0, 2);
```

And therein lies the problem! You can remove that line entirely, so you're left with `$moves` being the array of moves.

**Comment by jeremiahazurin** [comment]
Thank you. I'm really sorry, but I made the necessary edits and assume that my display in my index is now the problem, but I still don't understand what I'm doing wrong.  If I echo p1 and p2 to `moves` and `choice` (at least, I think I'm suppose to do that because they indicate the selection p1 made as well as p2's selection), isn't it supposed to return the confirmation message? Is it possible to `var_dump` this to see what I'm missing/what's being printed?

**Comment by susanBuck** [comment]
No worries, it's all about chipping away at the problem until you get the result you expect.

Here's your View code to display the results:

```php
<?php if ($showResults) { ?>
  P1 chose: <?php echo $results['moves']; ?>
  P2 chose: <?php echo $results['choice']; ?>
  }

  <?php if ($results['winner']) { ?>
    You won!
  <?php } else {?>
    You lost!
  <?php } ?>
<?php } ?>
```

Everything there hinges on `$showResults` being `true` - so if you're not getting the output you expect, you should look closer at `$showResults` - Where is it being set? Is it being set to what you expect? etc.

I can see it's being set in your `index-controller.php` file:

```php
if(isset($_SESSION['correct'])) {
    $correct = $_SESSION['correct'];
    $showResults = true;
    $_SESSION['correct'] = null;
} else {
    $showResults = false;
}
```

Based on the above, `$showResults` should be `true` *if* `$_SESSION['correct']` is set.

Let's add a `var_dump($_SESSION['correct'])` to check and see if its set:

![image](https://user-images.githubusercontent.com/237711/66875721-46d7a980-ef7d-11e9-9361-684f5a6101a3.png)

When I run the above code and submit the form, it reports that `$_SESSION['correct']` is `NULL` (i.e. not set):

![image](https://user-images.githubusercontent.com/237711/66875742-5525c580-ef7d-11e9-9b4d-774d3ce4a20d.png)

This explains why we weren't getting any results. So now we trace where `$_SESSION['correct']` is supposed to be initially set to understand why it's not set...

This happens in `process.php`... or it should happen in `process.php`, but what's actually happening there is you're setting a session called `moves`:

![image](https://user-images.githubusercontent.com/237711/66875796-83a3a080-ef7d-11e9-9589-2f06e17f59e9.png)

And there's the disconnect - you're setting the session as `moves` but then trying to retrieve it as `correct`. Make these things consistent.

Once you fix that, you'll be closer:
![image](https://user-images.githubusercontent.com/237711/66875965-fc0a6180-ef7d-11e9-871e-51995016c9dc.png)

The results "You lost!" are displayed, but there's a problem with the `P1 Chose:` and `P2 Chose:` output - specifically it says `$results` is not defined. So again we begin the debugging process --- where is $results supposed to be defined? Is it being defined? If it is, and we do a var_dump does it have the values we expect? If not, why? etc.

**Comment by jeremiahazurin** [comment]
**where is $results supposed to be defined?** 
in process?
**Is it being defined?**
Yes: 
`$results = [`
    `"winner" => $winner,`
    `"moves" => $moves,`
    `"choice" => $choice,`
`];`

**we do a var_dump does it have the values we expect?**
`var_dumping` prints out an error message since `$results` is not defined...however, i thought I defined it in the code above? i think my syntax is wrong but i think my variables are correct, right?

**Comment by jeremiahazurin** [comment]
i think i know my error. i had `correct` instead of `results` variables in my controller. but now i still don't know how to display it properly on index. 

<?php if ($showResults) { ?>
  P1 chose: <?php echo $results['moves']; ?>
  P2 chose: <?php echo $results['choice']; ?>
  }

  `<?php if ($results['winner']) { ?>`
    `You won!`
  `<?php } else {?>`
   ` You lost!`
  `<?php } ?>`
`<?php } ?>`

i defined my results now (instead of `results`), is there a variable i'm missing?

**Comment by susanBuck** [comment]
`$results` is initially defined in `process.php`, yes. 

But it's then supposed to store it in the session and then redirect to `index.php`, where `index-controller.php` can extract it from the session.

However, here's the code you have in `process.php`:
```php
$results = [
    "winner" => $winner,
    "moves" => $moves,
    "choice" => $choice,
];

$_SESSION["correct"] = $moves; # This should not be set to $results, not $moves
```

We see the array `$results`...

But `$_SESSION["correct"]` is set to `$moves`... that's not what we want. It should be set to `$results`.

While we're here, lets be consistent in our naming - when storing `$results` in `$_SESSION` we should use they index name `results`. A lot of your issues are coming from inconsistencies in naming, so be on the look out for mistakes like that when debugging.

After making the above edit, that leaves us with this:

```php
$results = [
    "winner" => $winner,
    "moves" => $moves,
    "choice" => $choice,
];

$_SESSION["results"] = $results;
header("Location: index.php");
```

Following this up, let's make the naming choices in `index-controller.php` consistent, using `results` as the name when extracting from the SESSION and also when setting a $results variable:

```php
# index-controller.php
if (isset($_SESSION['results'])) { 
    $results = $_SESSION['results']; $_SESSION['results']
    $showResults = true;
    $_SESSION['results'] = null;
} else {
    $showResults = false;
}
```

After I make the above changes, I still see a notice:

![image](https://user-images.githubusercontent.com/237711/66879639-fd8f5600-ef8c-11e9-8b65-13f37037d383.png)


That notice is pointing to this line:
```html
P1 chose: <?php echo $results['moves']; ?>
```

We're trying to echo `$results['moves']` but PHP is telling us that's an array and it can't be echo'd. 

We have to figure out why it's an array, so we'll again trace it to the source, which is in `process.php`:

![image](https://user-images.githubusercontent.com/237711/66879686-3fb89780-ef8d-11e9-8aef-f22a43fb3c10.png)

From the above screenshot you can see `$moves` is defined as an array on line 6, and then we set `$results['moves']` to be that array on line 36.

Your goal here is to print out the player 1 move, so I don't think $moves is the array you want to be targeting; instead you want to be targeting $p1 as that has the player 1 move. Likewise, you want the $p2 info for player move.

Knowing this, we can restructure $results as follows:

```php
$results = [
    "winner" => $winner,
    "p1" => $p1,
    "p2" => $p2,
];
```

Then, coming back to your View file, we should update these lines:

```html
P1 chose: <?php echo $results['moves']; ?>
P2 chose: <?php echo $results['choice']; ?>
```

To be:

```html
P1 chose: <?php echo $results['p1']; ?>
P2 chose: <?php echo $results['p2']; ?>
```

**Comment by jeremiahazurin** [comment]
Thank you so much. I truly appreciate it!!!!! This has been immensely helpful

**Comment by susanBuck** [comment]
You're welcome; glad it's working! : )
