### ISSUE TITLE
php-cs-fixer.executablePath not allowing edits

### ISSUE THREAD

**Issue by Janeece** [susanBuck/e2-fall19#46]
I am able to edit the file path in settings.json per the notes, but when I save it, it reverts back to this:
"php-cs-fixer.executablePath": "${extensionPath}\\php-cs-fixer.phar", 

and I get an error message that it's unable to find the executable path.

**Comment by susanBuck** [comment]
Hi @Janeece -

How odd! 

Are you on Mac or Windows?

Does it revert back immediately on save, or is it the case that you save the changes, close settings, and then when you re-open settings its been reverted?

**Comment by susanBuck** [comment]
Follow-up: I found [this thread where others were describing a similar issue of the path reverting back...](https://github.com/junstyle/vscode-php-cs-fixer/issues/46)

Can you copy/paste the exact path you're using here?

**Comment by susanBuck** [comment]
One more follow-up: to test the path you're using is correct, run `head -n 10 /your/path/to/php-cs-fixer.phar` in command line. 

This will read the first 10 lines of the `php-cs-fixer.phar` file if it finds it. If not, it'll report back that it can't open the file and then you know there's a problem with the path.

Here's an example successful output from my Windows machine:
```bash
λ head -n 10 c:/Users/Susan/.vscode/extensions/junstyle.php-cs-fixer-0.1.127/php-cs-fixer.phar
#!/usr/bin/env php
<?php

/*
 * This file is part of PHP CS Fixer.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *     Dariusz Rumiński <dariusz.ruminski@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
```

**Comment by anyav77** [comment]
I also got an error: 
> PHP CS Fixer: executablePath not found, please check your settings. It will set to built-in php-cs-fixer.phar. Try again!

In my case, the path did not revert.  
I changed the forward slashes to back slashes:    
`
"php-cs-fixer.executablePath": "c:\\Users\\admin\\.vscode\\extensions\\junstyle.php-cs-fixer-0.1.127\\php-cs-fixer.phar"
`

Then, I saved it, closed the error message, and reopened VSC.
I do not see the error anymore.

**Comment by shcantrell** [comment]
@Janeece You may have already resolved this, but this article helped me: https://webstoked.com/fix-cannot-validate-php-vs-code/

**Comment by RGPhD** [comment]
Dear @Janeece,

Did you find the solution yet?  I am about to update my **VSCode Editor** and I was wondering if this happened after you updated to the newest version or if you already had the newest version on your PC.

Best,
Robelyn

**Comment by Janeece** [comment]
Thank you for all of the suggestions! I really appreciate the support.
I was traveling all this week so was unable to respond earlier.

I am using Windows.
I am still getting the error message.
When I ran the path from the command line, it validate. So it's not the path.
The exact path I'm using is: 
```
c:/Users/Janee/.vscode/extensions/junstyle.php-cs-fixer-0.1.127/php-cs-fixer.phar
```

Leaving it as the default path didn't work either.
```
 "${extensionPath}\\php-cs-fixer.phar"
```
Changing forward slashes to backward slashed did not resolve the issue. 

I am using the version provided in the notes, 0.1.127

I uninstalled php cs fixer and reinstalled it. Still not working.

I'll be traveling again all of this coming week, so I'll have to try to figure it out later.

**Comment by susanBuck** [comment]
@Janeece It sounds like you've thoroughly tried all the options. I'm a bit stumped on this one without being able to debug it "in person".

If you'd like to set up a time to screenshare and work through this together, send me an email when you're back in town and we can set up a time.

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any problems are still pending.
