### ISSUE TITLE
DigitalOcean - Server Problem - This site can’t be reached

### ISSUE THREAD

**Issue by nbandach** [susanBuck/e2-fall19#48]
I have a problem with my Digital Ocean server, when I try to access p3 (that I submitted a week ago), I get the message:

**This site can’t be reached**
p3.natbandach.me refused to connect.
Search Google for natbandach me
ERR_CONNECTION_REFUSED

I was trying to go through these steps: https://www.digitalocean.com/community/questions/help-me-to-fix-err_connection_refused but I am a bit lost...

Any visual help would be more than welcome.

**Comment by nbandach** [comment]
Hi @susanBuck - my droplet is active, and this is the IP: 104.248.204.1
![Screenshot 2019-10-24 at 01 07 15](https://user-images.githubusercontent.com/6833462/67440831-c65b1d80-f5fa-11e9-9e31-90ac23a4ea7b.png)

**Comment by nbandach** [comment]
Yes, I am able to access the server, however the restart gives back:

```
root@e2:~# service apache2 restart
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xe" for details.
```

I went through all the steps in the instructions to add you to my server. Let me know if your could access! Thanks for your help.

**Comment by susanBuck** [comment]
Confirming I was able to SSH into your server. 👍 
I've got to run to some meetings right now, but I'll take a closer look at this when I'm back later today and follow-up then.

**Comment by nbandach** [comment]
Thanks! I am on CET time (Barcelona), so I will probably see it tomorrow.

**Comment by susanBuck** [comment]
Update:

I logged into your server and attempted to do an Apache restart. Like you saw, this resulted in an error:

```
root@e2:~# service apache2 restart
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xe" for details.
```

When I ran the suggested command of `journalctl -xe` for details, it produced the following info:

```
-- Unit apache2.service has begun starting up.
Oct 25 02:10:22 e2 apachectl[13214]: apache2: Syntax error on line 225 of /etc/apache2/apache2.conf: Syntax error on line 44 of /etc/apache2/sites-enabled/00
Oct 25 02:10:22 e2 apachectl[13214]: Action 'start' failed.
Oct 25 02:10:22 e2 apachectl[13214]: The Apache error log may have more information.
Oct 25 02:10:22 e2 systemd[1]: apache2.service: Control process exited, code=exited status=1
Oct 25 02:10:22 e2 systemd[1]: apache2.service: Failed with result 'exit-code'.
Oct 25 02:10:22 e2 systemd[1]: Failed to start The Apache HTTP Server.
```

This indicated there's a syntax error in your VirtualHost config file (`/etc/apache2/sites-enabled/000-default.conf`) so I took a look at that and spotted the problem:

![image](https://user-images.githubusercontent.com/237711/67538056-e4348b00-f6ab-11e9-8240-567d478ccb00.png)

Once I fixed that, Apache restarted fine and you're back in business! : )

**Comment by nbandach** [comment]
Hi Susan, you are a life saver! I spent quite a lot of time trying to troubleshoot this.. And all because of the tag...
Anyway... Note taken. Thanks a lot!

**Comment by susanBuck** [comment]
np!
