### ISSUE TITLE
PHP Class Exercise

### ISSUE THREAD

**Issue by shcantrell** [susanBuck/e2-fall19#49]
Hello, 

This is my code for the Class exercise, which works:

```php
class Person
{
    //Properties
    public $firstName;
    public $lastName;
    public $age;

    //Method
    public function getFullName()
    {
        echo $this->firstName . ' ' . $this->lastName . PHP_EOL;
    }
    public function getClassification()
    {
        return $classification = ($this->age >= 18) ? 'adult' : 'minor';
    }
}

$person = new Person();

$person->firstName = 'John';
$person->lastName = 'Harvard';
$person->age = 45;

echo $person->getFullName();
echo $person->firstName;
echo $person->getClassification();
```

When I try to use the following, it does not work. Should it work and if so, what am I misunderstanding?

```php
$person = new Person('John', 'Harvard', 45);

echo $person->getFullName();
echo $person->firstName;
echo $person->getClassification();
```

Thanks!

**Comment by philyuska** [comment]
my 2 cents would be you are missing the `__constructor` method.
If it is present in your class it will get called when you instantiate it via `new` and pass it some variables.
In Professor Bucks example, it accepts 3 variables firstName, lastName and age, that's where `('John', 'Harvard', 45)` get stored and is most likely what is behind the issue you are facing.
 
```php
    public function __construct(string $firstName, string $lastName, int $age)
    {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->age = $age;
    }
```

Cheers

**Comment by shcantrell** [comment]
@philyuska and @susanBuck 

Great! I will add this in and will you know my progress. :)

Thanks.

**Comment by shcantrell** [comment]
@philyuska and @susanBuck

Yep! That did it. Thanks. I had the construct function there before, but did not define the variables, so it did not work. Now I know what was missing!

Thanks, again.

**Comment by shcantrell** [comment]
@philyuska and @susanBuck

Just started watching part 2 of week 8 - HA!

**Comment by susanBuck** [comment]
@shcantrell Glad it's all sorted out! : )
