### ISSUE TITLE
Git Error Post Mac Update 

### ISSUE THREAD

**Issue by lindsaymshepard** [susanBuck/e2-fall19#50]
LindsayShepard@Lindsays-MBP ~ % git status
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
LindsayShepard@Lindsays-MBP ~ % 

I have finished the peer review and was trying to add it to my repository via command line, but it won't let me add it.

**Comment by susanBuck** [comment]
A student on my other class actually just posted a fix for this, so I'll just paste his answer in here below. : )

---

Those updating to MacOS Catalina will need to update your command line tools to get Git to function properly again.

To fix this, run the following command:

```
$ xcode-select --install
```

Continue to follow the prompts until everything is installed. Once finished, restart the terminal.

[Solution from stackoverflow](https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa).

---

If that doesn't fix things for you, @lindsaymshepard - let us know.

**Comment by lindsaymshepard** [comment]
Thank you! This worked.
