### ISSUE TITLE
P3 Sampling

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall19#52]
Hi everyone -

FYI I just released Project 3 grades/feedback in Canvas.

Below's a sampling of projects from your classmates to check out. I'm including the production URL as well as the Github URL if you want to explore the code underneath (which you're encouraged to do).

http://p3.shcantrell.me
https://github.com/shcantrell/e2/tree/master/p3

http://p3.chantelledmello.me
https://github.com/chantelledmello/e2/tree/master/p3

http://p3.robelyngarcia.me
https://github.com/RGPhD/e2/tree/master/p3

http://p3.antoniephp.com
https://github.com/AntonieKowal/e2/tree/master/p3

http://p3.shawnasummers.xyz
https://github.com/smsummers1/e2/tree/master/p3

http://p3.junkpileart.com/p3-index.php
https://github.com/MPVaccaro/e2/tree/master/p3

http://p3.tymabus.fun
https://github.com/philyuska/e2/tree/master/p3

**Comment by shcantrell** [comment]
@chantelledmello - super cool 
@shawnasummers - I really liked the way you listed my prior guesses
@junkpileart - whoa...I might actually use this
@tymabus - WOW - super complex

**Comment by RGPhD** [comment]
Dear Professor @susanBuck,

Thanks for sharing.

@AntonieKowal I enjoyed playing your game, and **especially** liked how you had two games on one page.  *Well done!*

I have been trying this with my practice Apps locally.

Robelyn
