### ISSUE TITLE
return $winningScore doesn't reflect outside the function

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e2-fall19#54]
This is a followup on week 7.  
I tried to create a function for the final score, and I can't get the results displayed on the index.php
On the localhost, I get a notice:
> and the final winner is... with
Notice: Undefined variable: winningScore in C:\xampp\htdocs\e2\practice\week7-code-design\index.php on line 34
points.
```php
    <h3>and the final winner is... <?= $finalwinner ?> with
        <?= $winningScore ?> points.
    </h3>
```

I'm able to get the score in the index-controller.php inside the function using         `var_dump($winningScore);`
but it is not accessible outside the function.  I tried using both global and local variables.
```php
<?php

$winner = [];
$finalwinner = null;
$player1scores = 0;
$player2scores = 0;
$result = [];



for ($i = 0; $i < 5; $i++) {
    $player1Move = makeMove();
    $player2Move = makeMove();
    $results[$i]['player1'] = $player1Move;
    $results[$i]['player2'] = $player2Move;
 
    if ($player1Move == $player2Move) {
        $results[$i]['winner'] = 'a tie';
        $player1scores += 0.5;
        $player2scores += 0.5;
    } elseif (($player1Move == "rock" and $player2Move == "scissors") || ($player1Move == "paper" and $player2Move == "rock") || ($player1Move == "scissors" and $player2Move == "paper")) {
        $results[$i]['winner'] = 'Player 1';
        $player1scores += 1;
    } else {
        $results[$i]['winner'] = 'Player 2';
        $player2scores += 1;
    }
}
# Calculate the final winner, based on Player A scores



function finalScore($player1scores, $player2scores)
{
    $winningScore = 0;
    if ($player1scores > $player2scores) {
        $finalwinner = "Player A";
        $winningScore = $player1scores;
        var_dump($winningScore);
        return $winningScore;
    } elseif ($player1scores == $player2scores) {
        $finalwinner = "It's a tie";
        $winningScore = $player1scores;
        var_dump($winningScore);
        return $winningScore;
    } else {
        $finalwinner = "Player B";
        $winningScore = $player2scores;
        var_dump($winningScore);
        return $winningScore;
    }
}
var_dump($winningScore); // returns NULL
finalScore($player1scores, $player2scores);
```

[https://github.com/anyav77/e2/commit/bc4b8492afadd34ab5703a7ac911db6c553b2e86](https://github.com/anyav77/e2/commit/bc4b8492afadd34ab5703a7ac911db6c553b2e86)
[http://practice.atozez.com/week7-code-design/](http://practice.atozez.com/week7-code-design/)

**Comment by philyuska** [comment]
looks like the user defined function `finalScore` is returning the value `$winningScore` so when you call it you need to either accept the return value in a variable or you could echo it directly.

e.g. accept the return value index-controller.php
```php
$winningScore = finalScore($player1scores, $player2scores);
```
or echo the value directly
```php
<?=finalScore($player1scores, $player2scores)?>
```

**Comment by susanBuck** [comment]
👍to @philyuska's suggestion.

I'd lean towards this approach:

```php
$winningScore = finalScore($player1scores, $player2scores);
```

Just because `<?=finalScore($player1scores, $player2scores)?>` feels like unncessary logic in the view.

This could be solved with global variables, but it's better to have a function return its results and capture those results in a variable. This better encapsulates the function making the whole program easier to debug.

**Comment by anyav77** [comment]
Thank you!  It helped to post the $winningScore.  

Is it possible to return two values from the finalscore function and reflect them in index.php? 

I tried to post the final winner, but I got a notice: 

> and the final winner is...
Notice: Array to string conversion in C:\xampp\htdocs\e2\practice\week7-code-design\index.php on line 33
Array with
Notice: Array to string conversion in C:\xampp\htdocs\e2\practice\week7-code-design\index.php on line 34
Array points.

```php
function finalScore($player1scores, $player2scores)
{
    $winningScore = 0;
    $finalwinner = null;
    if ($player1scores > $player2scores) {
        $finalwinner = "Player A";
        $winningScore = $player1scores;
        //var_dump($winningScore);
        return array($winningScore, $finalwinner);
    } elseif ($player1scores == $player2scores) {
        $finalwinner = "It's a tie";
        $winningScore = $player1scores;
        //var_dump($winningScore);
        return array($winningScore, $finalwinner);
    } else {
        $finalwinner = "Player B";
        $winningScore = $player2scores;
        //var_dump($winningScore);
        return array($winningScore, $finalwinner);
    }
}
//var_dump($winningScore); // returns NULL
finalScore($player1scores, $player2scores);
$winningScore = finalScore($player1scores, $player2scores);
$finalwinner = finalScore($player1scores, $player2scores);
```

**Comment by susanBuck** [comment]
Yup, you can return multiple values - by doing what you did of storing those values in an array and returning that.

The error you have with this approach is where you're **retrieving** those values:

```
$winningScore = finalScore($player1scores, $player2scores);
$finalwinner = finalScore($player1scores, $player2scores);
```

What happens here is `$winningScore` and `$finalWinner` are set to the array of results, not the individual pieces of that array that represent the winningScore and finalWinner.

Here's an alternative approach:

```php
$results = finalScore($player1scores, $player2scores);
$winningScore = $results[0];
$finalwinner = $results[1];
```

The `0` and `1` can be a little obscure there though - you'd have to trace the results back to the function to understand what values is at 0 and 1. Instead, be more explicit with named indexing so your return looks like this:

```php
return [
    'winningScore' => $winningScore, 
    'finalwinner' => $finalwinner
];
```

Then, when you retrieve those values, it can look like this:
```
$results = finalScore($player1scores, $player2scores);
$winningScore = $results['winningScore'];
$finalwinner = $results['finalwinner];
```



Side note: I suggest being consistent with your casing. Right now you have `$winningScore` as `lowerCamelCase` and `$finalwinner` as `alllowercase`; ideally it should be `$finalWinner` (`lowerCamelCase`). 

Little inconsistencies like that can cause frustrating bugs when you're working with the variables in different places and having to remember what casing style you're using.

Let me know if you have any follow-up questions about the above!

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any problems are still pending.
