### ISSUE TITLE
Is the peer review supposed to show up on our domain, too?

### ISSUE THREAD

**Issue by jeremiahazurin** [susanBuck/e2-fall19#57]
My link is [http://peer-review.jae2.me/](http://peer-review.jae2.me/) and I've followed the [production server](https://hesweb.dev/e2/notes#/production-server/summary) instructions clearly. However, my "http://peer-review.jae2.me/" link is not working. 

Is my link supposed to be "peer-review.**md**.jae2.me? Is my VirtualHost supposed to have "/path/to/htdocs/e2/peer-review.md" or "/path/to/htdocs/e2/peer-review" (without the .md)?

It shows up on my [Github](https://github.com/jeremiahazurin/e2/blob/master/peer-review.md)

**Comment by susanBuck** [comment]
Hi Jeremiah - You don't need to worry about deploying/running the peer-review file from your production server. 

All you have to submit is the URL to the file on Github, <https://github.com/jeremiahazurin/e2/blob/master/peer-review.md>

Ref: Step 5:

![image](https://user-images.githubusercontent.com/237711/67809711-a189fe80-fa6f-11e9-8c98-f9ac14d121f2.png)

**Comment by jeremiahazurin** [comment]
Thanks!

Sincerely,
Jeremiah Azurin
