### ISSUE TITLE
Composer install rock-paper-scissors - 'composer' is not recognized

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e2-fall19#59]
I tried the command, and I got the error:

> composer require susanbuck/rock-paper-scissors 'composer' is not recognized as an internal or external command, operable program or batch file.

I'm a Windows user.

**Comment by susanBuck** [comment]
Were you able to get through all the steps here [Composer Windows](https://hesweb.dev/e2/notes#/php/composer-windows) and successfully get composer installed?

**Comment by anyav77** [comment]
I have installed the composer prior to attempting the command.
It shows as installed successfully in the programs.
![composer installed](https://user-images.githubusercontent.com/1045307/67985969-382cfb80-fbe7-11e9-931f-1f0981f119d7.png)

**Comment by susanBuck** [comment]
Were you able to invoke `composer` from the command line after installing?

[ref](https://hesweb.dev/e2/notes#/php/composer-windows?jump=installing-composer-on-windows):
![image](https://user-images.githubusercontent.com/237711/67986123-b8138f80-fc00-11e9-9f3e-c9dedd886aed.png)

If you haven't already done so, make sure you **completely close and re-open Cmder** - otherwise it won't recognize that Composer has been installed.

If that doesn't do the trick, can you run `where.exe php` and report back on what it says? I want to make sure your PHP executable is pointing to XAMPP's PHP; if not, it could be impacting how your Composer path was set up.

**Comment by anyav77** [comment]
I restarted the computer.

- ran "composer" in the commander; got the installation confirmation
- ran "composer require susanbuck/rock-paper-scissors"
- The composer ran, but the package was not downloaded to "week8". Note: xampp was not running at that time.
- ran "where.exe php"; result: "C:\xampp\php\php.exe"

> 
> C:\Users\admin
> λ composer
>    ______
>   / ____/___  ____ ___  ____  ____  ________  _____
>  / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
> / /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
> \____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
>                     /_/
> Composer version 1.9.0 2019-08-02 20:55:32
> 
> Usage:
>   command [options] [arguments]
> 
> Options:
>   -h, --help                     Display this help message
>   -q, --quiet                    Do not output any message
>   -V, --version                  Display this application version
>       --ansi                     Force ANSI output
>       --no-ansi                  Disable ANSI output
>   -n, --no-interaction           Do not ask any interactive question
>       --profile                  Display timing and memory usage information
>       --no-plugins               Whether to disable plugins.
>   -d, --working-dir=WORKING-DIR  If specified, use the given directory as working directory.
>       --no-cache                 Prevent use of the cache
>   -v|vv|vvv, --verbose           Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3
> for debug
> 
> Available commands:
>   about                Shows the short information about Composer.
>   archive              Creates an archive of this composer package.
>   browse               Opens the package's repository URL or homepage in your browser.
>   check-platform-reqs  Check that platform requirements are satisfied.
>   clear-cache          Clears composer's internal package cache.
>   clearcache           Clears composer's internal package cache.
>   config               Sets config options.
>   create-project       Creates new project from a package into given directory.
>   depends              Shows which packages cause the given package to be installed.
>   diagnose             Diagnoses the system to identify common errors.
>   dump-autoload        Dumps the autoloader.
>   dumpautoload         Dumps the autoloader.
>   exec                 Executes a vendored binary/script.
>   global               Allows running commands in the global composer dir ($COMPOSER_HOME).
>   help                 Displays help for a command
>   home                 Opens the package's repository URL or homepage in your browser.
>   i                    Installs the project dependencies from the composer.lock file if present, or falls back on the comp
> oser.json.
>   info                 Shows information about packages.
>   init                 Creates a basic composer.json file in current directory.
>   install              Installs the project dependencies from the composer.lock file if present, or falls back on the comp
> oser.json.
>   licenses             Shows information about licenses of dependencies.
>   list                 Lists commands
>   outdated             Shows a list of installed packages that have updates available, including their latest version.
>   prohibits            Shows which packages prevent the given package from being installed.
>   remove               Removes a package from the require or require-dev.
>   require              Adds required packages to your composer.json and installs them.
>   run                  Runs the scripts defined in composer.json.
>   run-script           Runs the scripts defined in composer.json.
>   search               Searches for packages.
>   self-update          Updates composer.phar to the latest version.
>   selfupdate           Updates composer.phar to the latest version.
>   show                 Shows information about packages.
>   status               Shows a list of locally modified packages, for packages installed from source.
>   suggests             Shows package suggestions.
>   u                    Upgrades your dependencies to the latest version according to composer.json, and updates the compos
> er.lock file.
>   update               Upgrades your dependencies to the latest version according to composer.json, and updates the compos
> er.lock file.
>   upgrade              Upgrades your dependencies to the latest version according to composer.json, and updates the compos
> er.lock file.
>   validate             Validates a composer.json and composer.lock.
>   why                  Shows which packages cause the given package to be installed.
>   why-not              Shows which packages prevent the given package from being installed.
> 
> C:\Users\admin
> λ git commit "Modified the title"
> fatal: not a git repository (or any of the parent directories): .git
> 
> C:\Users\admin
> λ composer require susanbuck/rock-paper-scissors
> Using version ^0.1.3 for susanbuck/rock-paper-scissors
> ./composer.json has been created
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Package operations: 1 install, 0 updates, 0 removals
>   - Installing susanbuck/rock-paper-scissors (0.1.3): Downloading (100%)
> Writing lock file
> Generating autoload files
> 
> C:\Users\admin
> λ

> C:\Users\admin
> λ where.exe php
> C:\xampp\php\php.exe

![week8](https://user-images.githubusercontent.com/1045307/68052436-ddf36f80-fca6-11e9-99f2-5e2810a6a7cc.png)

**Comment by susanBuck** [comment]
Ok, so it looks like Composer is confirmed as installed as working.

You said you ran `composer require susanbuck/rock-paper-scissors` but the package was not downloaded to week8.

Looking at your history of commands, it looks like you ran the command when you were in your ` `c:\Users\admin` directory.

Move into your `week8` directory and try it again.

**Comment by anyav77** [comment]
Thank you! It helped.
