### ISSUE TITLE
Week 9: Additional step required for Mac users when setting up framework (file_put_contents - failed to open stream: Permission denied)

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall19#62]
Hi everyone,

FYI there's one more step **Mac users** need to take after setting up a e2framework application that I did not cover in the lecture videos.

The step is to run this command (within the project directory):

```
$ sudo chmod -R 777 cache
```

This makes it so that the `cache/` directory is writable by the server and is necessary because the framework will write some cache files there. This step is not necessary for Window’s users as the server has sufficient privileges.

I've updated the notes to reflect this step.

Let me know if you run into any issues with this and apologies for any confusion it might have caused by skipping this step in the lecture videos! I have my XAMPP server configured to run as my admin user so it wasn't an issue I faced.

**Comment by chantelledmello** [comment]
Hi Prof,

I'm still having an issue with accessing my zipfoods.loc local URL. 

Attaching a series of screenshots to show (1) the chmod command being run in terminal (2) the browser error message on attempting to access 'zipfoods.loc', and (3) the browser error message on attempting to access the index.php file in the root/public folder directly

*Terminal View*
<img width="775" alt="Screen Shot 2019-11-05 at 2 49 05 PM" src="https://user-images.githubusercontent.com/26146422/68236389-78232280-ffdb-11e9-9076-9e7911fa7ba8.png">

*Browser View: zipfoods.loc*
<img width="1426" alt="Screen Shot 2019-11-05 at 2 48 40 PM" src="https://user-images.githubusercontent.com/26146422/68236476-9db02c00-ffdb-11e9-8f83-68fcc1b251e8.png">

*Browser View: index.php*
<img width="1426" alt="Screen Shot 2019-11-05 at 2 48 57 PM" src="https://user-images.githubusercontent.com/26146422/68236484-9f79ef80-ffdb-11e9-90e5-c0a1c16eb161.png">

**Comment by chantelledmello** [comment]
UPDATE:

I went into the ```index.php``` file to find the line that was throwing the error. 

```php

# Initialize Composer autoloading
require DOC_ROOT.'/vendor/autoload.php';
```

I then followed the path to the vendor directory and found this line of code:

```php
require_once __DIR__ . '/composer/autoload_real.php';
```

I then went into the composer directory but for some reason, there doesn't seem to be any ```autoload_real.php``` file at all (see attached screenshot for reference)

<img width="317" alt="Screen Shot 2019-11-05 at 2 55 59 PM" src="https://user-images.githubusercontent.com/26146422/68236877-62622d00-ffdc-11e9-89f9-eddc68c4ec4d.png">

**Comment by kking1204** [comment]
Thank you! I was *this* close to freaking out.
