### ISSUE TITLE
Framework Install Error: JIT compilation failed: no more memory

### ISSUE THREAD

**Issue by chantelledmello** [susanBuck/e2-fall19#63]
Hi Prof,

I tried to install the E2 Framework as per the instructions in the notes and the lecture but I get this screen or errors/horrors instead! 

<img width="1206" alt="Screen Shot 2019-10-30 at 3 07 02 PM" src="https://user-images.githubusercontent.com/26146422/67890258-c7260f00-fb26-11e9-97ad-fa5b2c0e829f.png">

Help, please! 😭

**Comment by susanBuck** [comment]
Hi @chantelledmello -

It looks like you're hitting some memory limits with PHP.

Can you share the output of the commands `which php` and also `php --ini` ? This will provide some details about your PHP setup which we'll use to debug further.

**Comment by chantelledmello** [comment]
Sure, this is what I get. 
<img width="504" alt="Screen Shot 2019-10-30 at 3 12 57 PM" src="https://user-images.githubusercontent.com/26146422/67890712-98f4ff00-fb27-11e9-8d89-1c96bbb85c49.png">

**Comment by susanBuck** [comment]
I did some research and found [this post](https://stackoverflow.com/questions/53690624/errors-installing-composer-on-macos-jit-compilation-failed) which suggests disabling a particular feature in PHP as a workaround.

To do this, you should open your XAMPP `php.ini` file:

```bash
$ nano /Applications/XAMPP/xamppfiles/etc/php.ini
```

At the bottom of this file, add the following line:

```
pcre.jit=0
```

Save your changes and exit.

Attempt the create-project command again:
```
composer create-project --prefer-dist susanBuck/e2framework zipfoods
```

Let me know if that works or not.

**Comment by chantelledmello** [comment]
It worked....to an extent (?) It still says that it 'cannot create cache directory' 

<img width="1023" alt="Screen Shot 2019-10-30 at 3 39 51 PM" src="https://user-images.githubusercontent.com/26146422/67892567-58978000-fb2b-11e9-89b0-4073e3328bd9.png">

**Comment by susanBuck** [comment]
Great! 

Can you let me know what version of XAMPP you're running? Curious if it's different from mine/why I didn't experience the same problem on my end.

Regarding the **Cannot create cache directory** - it's not a critical problem. It means Composer is unable to write cache files. Composer should continue to function fine, it just won't be as optimized.

The following command should resolve that warning, as it will change ownership of your composer directory:

```
sudo chown -R $USER $HOME/.composer
```
