### ISSUE TITLE
vendor directory was pushed to github

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e2-fall19#65]
My week8 vendor directory was pushed to github:
https://github.com/anyav77/e2/tree/master/practice/week8/vendor

It was probably because I created .gitignore in the app directory rather than the main week8 directory.
Should I continue with the exercise instructions, or should I delete it from github and re-run the commands?

**Comment by susanBuck** [comment]
Here are the steps to fix this:

First, update/confirm the file `/week8/.gitignore` has `vendor` listed as one of the directories to ignore.

Then, within your `week8/` directory, make git "forget" the vendor directory with this command:

```bash
git rm -r --cached vendor
```

Note: it's not actually deleting the directory, just clearing it from git's memory.

Then stage and push all your changes. From within the `week8/` directory:

```
$ git add --all
$ git commit -m "Forgetting vendor directory"
```

At this point, the `vendor` directory should still exist locally, but should no longer be present if you view your repository at github.com.

Likewise, when you pull your latest changes on production, the `vendor` directory should be excluded.

If that doesn't do the trick, let me know.

**Comment by anyav77** [comment]
Thank you! It helped.

**Comment by anyav77** [comment]
I'm not sure if it's a new issue, but when I ran composer on the production, the command was not found:

```
root@e2:/var/www/html/e2/practice/week8# composer

Command 'composer' not found, but can be installed with:

apt install composer

root@e2:/var/www/html/e2/practice/week8#
```

**Comment by anyav77** [comment]
I realized that I had to install the composer first.  

Just to confirm: 
Do I need to install it in the e2 repository?

> root@e2:/var/www/html/e2#

**Comment by susanBuck** [comment]
The command to install composer can be run from any directory; it installs it globally on the system, not on a project-by-project basis.

The output you shared looks correct.
