### ISSUE TITLE
"ZipFoods.loc" works but not "/about"

### ISSUE THREAD

**Issue by jeremiahazurin** [susanBuck/e2-fall19#67]
Is the about page included in this framework or are we supposed to create it? I noticed that [Susan's Views folder has some blade files](https://github.com/susanBuck/e2/tree/master/zipfoods/views) but [mine doesn't](https://github.com/jeremiahazurin/e2/tree/master/zipfoods/views) when I git push'd. 

I have the zipfoods.loc page but not zipfoods.loc/about.

**Comment by susanBuck** [comment]
Skim through the Week 9 assignment - in the second question (Practice), I prompt you to create an About page.

**Comment by jeremiahazurin** [comment]
Gotcha, thank you!

**Comment by jeremiahazurin** [comment]
I think I'm missing something but something tells me the solution is simple.

To add the /about page, we're _not_ to simply add it on Github via "Create new file", right? We have to add it from the command line? 

If os, my line of thought is this:
1. Create the `about.blade.php` page (check). Saved it onto my desktop.
2. Open `zipfoods` folder and stage it (ie `git add`)
3. [Where my issue is] how does one `git add` it from desktop if the zipfoods file is a framework? The framework repository isn't downloaded onto my computer (I think, since I just cloned it via [setup](https://hesweb.dev/e2/notes#/php/frameworks/setup).

**Comment by susanBuck** [comment]
Do not add the file via Github.
Do not add the file via command line.
Do not create the file on your desktop and then try to get it into zipfoods.

You could do all of the above, but that's not how we've been working on our projects.

Typically we have our projects open in our code editor (VSCode or whatever editor you're using). 

There we make edits - whether it be changing existing files, **adding new files**, etc. 

Then we test those edits in the browser, and continue making edits until things are working as we want them to.

Then, when we've reached a stopping point, we stage/commit/push our work to Github.

**Comment by jeremiahazurin** [comment]
Thanks! I haven't been adding via Github, and I have been using VSCode. I saved it on my desktop so that I just know where to retrieve it. But then I just realized that zipfoods is in htdocs so I can save my about page in VSCode in the zipfoods folder

**Comment by susanBuck** [comment]
Sounds like you're on the right track. 👍

**Comment by jeremiahazurin** [comment]
So I'm pretty sure I'm getting closer and closer but am still not seeing the about page. 

**What I'm Doing/Did**
1. Created the php `about` file in VSCode, saved to appropriate zipfoods/views folder
2. Commit/pushed my changes

**What I'm still not seeing**
1. About page

**What I think my problem is**
1. I have to edit my routes.php file to:
```
<?php

return [
    '/' => ['AppController', 'index'],
    '/about' => ['AppController', 'about'],
];

```

 and my vendor file, too, according to the fatal error message:
<img width="1461" alt="Screen Shot 2019-11-05 at 02 03 18" src="https://user-images.githubusercontent.com/16971379/68185816-7bcd8f80-ff70-11e9-9b60-74f1a70bafaf.png">

although (and i'm really not sure), I add another superglobal for about in `vendor/susanbuck/e2core/src/app.php`?

**Comment by susanBuck** [comment]
Did you create a method called `about` in the `AppController`?

**Comment by jeremiahazurin** [comment]
I see. thank you, i hadn't. that fixed the issue. I'm still quite confused about methods apparently. Will need to revisit them again. 

Thanks so much!

**Comment by susanBuck** [comment]
No problem. 

For a review, re-watch the Week 9, Part 6 video starting at the 3:36 mark ([link](https://youtu.be/SqVZOz0c_tI?t=216)) up until roughtly 10:11.

This includes the process where I create the *Contact* page, which is essentially the same procedures needed to create an *About* page.
