### ISSUE TITLE
Can't Access Zipfoods Locally

### ISSUE THREAD

**Issue by chantelledmello** [susanBuck/e2-fall19#68]
Hi Prof,

I'm still having an issue with accessing my zipfoods.loc local URL. 

Attaching a series of screenshots to show (1) the chmod command being run in terminal (2) the browser error message on attempting to access 'zipfoods.loc', and (3) the browser error message on attempting to access the index.php file in the root/public folder directly

*Terminal View*
<img width="775" alt="Screen Shot 2019-11-05 at 2 49 05 PM" src="https://user-images.githubusercontent.com/26146422/68236389-78232280-ffdb-11e9-9076-9e7911fa7ba8.png">

*Browser View: zipfoods.loc*
<img width="1426" alt="Screen Shot 2019-11-05 at 2 48 40 PM" src="https://user-images.githubusercontent.com/26146422/68236476-9db02c00-ffdb-11e9-8f83-68fcc1b251e8.png">

*Browser View: index.php*
<img width="1426" alt="Screen Shot 2019-11-05 at 2 48 57 PM" src="https://user-images.githubusercontent.com/26146422/68236484-9f79ef80-ffdb-11e9-90e5-c0a1c16eb161.png">

**Comment by susanBuck** [comment]
@chantelledmello - 
Can you share the contents of your VirtualHosts config file? (`/Applications/XAMPP/etc/extra/httpd-vhosts.conf`).

When you visit zipfoods.loc and see Access forbidden, it suggests to me there's a problem with how your VirtualHosts file is set up, so we should start there.

The warnings you're getting when trying to visit `http://localhost/e2/zipfoods/public/` directly are expected - they're occuring because the application is designed to be accessed with `public` as the document root.

**Comment by susanBuck** [comment]
Follow-up with two additional things I thought of:

1) Make sure you restarted your XAMPP Apache server after editing the VirtualHosts file
2) You can run the command `/Applications/XAMPP/bin/httpd -S` to check the VirtualHosts files for any issues. [ref](https://hesweb.dev/e2/notes#/local-server/local-domains?jump=troubleshooting)

**Comment by chantelledmello** [comment]
Sure! Here's the block of text I added to my VirtualHosts file:

```php

#Week 8 Practice Zip Foods App
<VirtualHost *:80>
    ServerName: zipfoods.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e2/practice/zipfoods/public
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e2/practice/zipfoods/public>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
        Require all granted
    </Directory>
</VirtualHost>

```

As for the other two issues, yup, I restarted the server again and no dice, and here's what the command gives me:

<img width="479" alt="Screen Shot 2019-11-05 at 5 40 49 PM" src="https://user-images.githubusercontent.com/26146422/68248455-3c945280-fff3-11e9-84f4-45e0ac82f75c.png">

**Comment by susanBuck** [comment]
You should remove the colon after ServerName:

This:
```
ServerName: zipfoods.loc
```

Should be:
```
ServerName zipfoods.loc
```

**Comment by chantelledmello** [comment]
Ah! 🙈How silly of me. I spent over an hour trying to debug this thing!

**Comment by susanBuck** [comment]
Great; np!
