### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by lindsaymshepard** [susanBuck/e2-fall19#70]
After deploying the latest code changes (from the beginning of Week 10 Part 2 video) I ran git pull and got the message 

fatal: not a git repository (or any of the parent directories): .git

I have never had this issue before- not sure if I did something wrong

**Comment by susanBuck** [comment]
This error occurs when you try to run git commands in a directory that is not managed by git.

From which directory are you running the command?

**Comment by susanBuck** [comment]
Odd - can you run the following three commands and share the full output:

1. `pwd`  (show the present working directory)
2. `ll` (show the directory contents)
3. `git status`

For reference, here's what it looks like on my end:

```bash
root@e2:/var/www/html/e2# pwd
/var/www/html/e2
root@e2:/var/www/html/e2# ll
total 44
drwxr-xr-x 9 root     root     4096 Nov  5 18:20 ./
drwxrwxr-x 4 www-data www-data 4096 Nov  5 18:20 ../
drwxr-xr-x 8 root     root     4096 Nov  6 16:39 .git/
-rw-r--r-- 1 root     root       54 Nov  5 18:20 README.md
drwxr-xr-x 2 root     root     4096 Nov  5 18:20 p2/
drwxr-xr-x 2 root     root     4096 Nov  5 18:20 p3/
-rw-r--r-- 1 root     root     2103 Nov  5 18:20 peer-review.md
drwxr-xr-x 7 root     root     4096 Nov  5 18:20 practice/
drwxr-xr-x 2 root     root     4096 Nov  5 18:20 week7/
drwxr-xr-x 3 root     root     4096 Nov  5 18:20 week8/
drwxr-xr-x 8 root     root     4096 Nov  5 23:13 zipfoods/
root@e2:/var/www/html/e2# git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by lindsaymshepard** [comment]
I just ran it again and it seems to be working now. Not sure what happened, but my computer did restart last night and have an update so maybe something fixed itself then. Thank you!

**Comment by susanBuck** [comment]
Glad it's working! :-) I've had this happen to me when I think I'm running commands in a certain directory, but I'm not actually in the correct/expected directory.
