### ISSUE TITLE
Unable to install mbstring PHP module

### ISSUE THREAD

**Issue by tasneemmunshi** [susanBuck/e2-fall19#73]
Hi there - I am trying to follow the steps in video # 2 for this week ("Part 2: Deploy to Production"), and in the very first step where you note to install the PHP module 'mbstring' - I am unfortunately having difficulty getting past that part.  Upon trying to run the first command 'apt install php7.2-mbstring', I am receiving an error, see screenshot below.  Any guidance/insight would be much appreciated - thank you!

![Screen Shot 2019-11-06 at 10 07 58 PM](https://user-images.githubusercontent.com/54759686/68356968-d9cdb480-00e1-11ea-9653-9a42ad7cd672.png)

**Comment by susanBuck** [comment]
Hi @tasneemmunshi - From your output, it looks like maybe you're running the command locally? 

You should SSH into your production server (DigitalOcean) and run the command there.

**Comment by tasneemmunshi** [comment]
Ahhh good point, how did I miss that bit!?  Silly over sight on my part!  My apologies... 

Thanks for the quick response and direction!

**Comment by susanBuck** [comment]
No worries - happens to us all sometimes. : )
