### ISSUE TITLE
products/index.blade.php single/double quotes issue

### ISSUE THREAD

**Issue by philyuska** [susanBuck/e2-fall19#74]
this line of code is being misinterpreted by visual studio code
```php
<a href='/product?id={{ $product[' id'] }}' />
```
the reuse of single quotes to encapsulate the href tag and $product['id'] is causing an extra space to be inserted and causing some unwanted issues

```html
<div id='product-index'>
<a href='/product?id=<br />
<b>Notice</b>:  Undefined index:  id in <b>C:\xampp\htdocs\e2\zipfoods\cache\2afe0a54a71756742e5a1f9fe4ccd718afa83b99.php</b> on line <b>11</b><br />
'>
```

The solution appears to be to encapsulate one or the other using double quotes, but i am not sure which one if any would be the right solution.
```

Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by susanBuck** [comment]
Either of these should work:

Use single quotes to encapsulate the href value, then double quotes within the PHP expression:
```html
<a href='/product?id={{ $product["id"] }}' />
```

Or do the inverse and use double quotes on the outside and single quotes on the inside:
```html
<a href="/product?id={{ $product['id'] }}" />
```

If you use the same type of quotes for both, it interrupts the outer href value.

If the above solutions don't work, let me know!

**Comment by philyuska** [comment]
both work, just wasn't sure which one to use :-), thank you!

**Comment by susanBuck** [comment]
Great : ) 

re: which to use - It's a preference thing.

I like to use single quotes as my "primary quote" technique in code. I like that it's easier to type (don't have to hold shift) and visually it's cleaner than a double quote.

Then, when I need to mix quotes - as in the example you showed - I use double quotes as the "secondary" quote on the insides.
