### ISSUE TITLE
http://zipfoods.hesweb.xyz/product and http://zipfoods.robelyngarcia.me/product pages return HTTP ERROR 500 on production

### ISSUE THREAD

**Issue by RGPhD** [susanBuck/e2-fall19#75]
Dear Professor @susanBuck,

Since we do not have a link/path to the /product URL, does it matter if our product path/page is blank and returns the ```HTTP ERROR 500```?  I just noticed that it does not return my custom missing view or the error 404 view like my other nonexistent pages.  I thought I missed a step from the videos, but after going through all of my code I decided to check your zipfoods code and page on production, and it shows up like mine:  <http://zipfoods.hesweb.xyz/product> and <http://zipfoods.robelyngarcia.me/product>.

**Should I add a return and or show for the product path or wait until we make Week 11 updates?**

Kind regards,
Robelyn

P.S. Although a blank page shows on production, I receive the following errors on my local server:
**Fatal error:** ```Uncaught TypeError: Argument 1 passed to App\Products::getById() must be of the type int, null given, called in``` 
```C:\xampp\htdocs\e2\zipfoods\app\Controllers\ProductController.php on line 29 and defined in``` ```C:\xampp\htdocs\e2\zipfoods\app\Products.php:22 Stack trace: #0``` ```C:\xampp\htdocs\e2\zipfoods\app\Controllers\ProductController.php(29): App\Products->getById(NULL) #1```
```C:\xampp\htdocs\e2\zipfoods\vendor\susanbuck\e2core\src\App.php(81): App\Controllers\ProductController->show() #2```
```C:\xampp\htdocs\e2\zipfoods\public\index.php(15): E2\App->route() #3 {main} thrown in``` **C:\xampp\htdocs\e2\zipfoods\app\Products.php on line 22**

**Comment by janenycxo** [comment]
Hi Robin,

Were you able to resolve this error? I am having issues with something similar with the page not loading.

Jane

**Comment by RGPhD** [comment]
Dear @janenycxo,

Not yet; I tried creating a command to return a message for product but it returned a different syntax error.  Since we do not have a required direct link to view the **/product** path I think it is okay for this page to be blank on production.  I am uncertain, however I think it is due to the fact that our product route requires a product id.  I will keep trying different functions and return views to fix the isolated path issue.

Robelyn

**Comment by janenycxo** [comment]
I get this error: 
Notice: Undefined variable: products in C:\xampp\htdocs\e2\zipfoods\app\Controllers\ProductController.php on line 14

Fatal error: Uncaught Error: Call to a member function getAll() on null in C:\xampp\htdocs\e2\zipfoods\app\Controllers\ProductController.php:20 Stack trace: #0 C:\xampp\htdocs\e2\zipfoods\vendor\susanbuck\e2core\src\App.php(81): App\Controllers\ProductController->index() #1 C:\xampp\htdocs\e2\zipfoods\public\index.php(15): E2\App->route() #2 {main} thrown in C:\xampp\htdocs\e2\zipfoods\app\Controllers\ProductController.php on line 20

**Comment by RGPhD** [comment]
Dear @janenycxo,

Your <http://zipfoods.janenycxo.me> works for me.  However, your products page is not set up.

Robelyn

**Comment by RGPhD** [comment]
![Capture zipfoodsjane](https://user-images.githubusercontent.com/54469368/68567966-86c46c00-0417-11ea-81b5-30cd5b91cb6a.JPG)
![Capture zipfoodsjaneproductspage](https://user-images.githubusercontent.com/54469368/68567984-92b02e00-0417-11ea-920b-16e0f3f502a5.JPG)

**Comment by susanBuck** [comment]
Hi @RGPhD - You can ignore the fact that the route `/product` is non-functioning right now.

It's an edge case we need to address - what happens when route is triggered that is missing parameters?

I'll go over some ways to handle this in this week's (11) lectures, but in the interim - it's an interesting question to think about.

How might we address this? (Both from a programmatic perspective and a user-experience perspective)

**Comment by susanBuck** [comment]
Update: Check out the Week 11 Part 1 video for more details on this. : )

**Comment by RGPhD** [comment]
Hello Professor @susanBuck,
Thank you very much for the detailed solution!
Robelyn
