### ISSUE TITLE
Production server not deploying but the routes are working

### ISSUE THREAD

**Issue by janenycxo** [susanBuck/e2-fall19#76]
Hi Professor,

Is there any reason why my production server zipfoods.janenycxo.me would not deploy but the route zipfoods.janenycxo.me/about work?

I followed the instructions from lecture and the troubleshoot tips check out. Zipfoods ll display www data as expected.

before progressing I’d like to resolve this issue, appreciate your help!

Jane

**Comment by janenycxo** [comment]
Hi Professor,

Still trying to resolve this, and am attaching the screenshots.
[dgmde 2 week 10.docx](https://github.com/susanBuck/e2-fall19/files/3829625/dgmde.2.week.10.docx)

The document shows all files and their permissions, confirming the cache directory is owned by www-data and looks like:
drwxr-xr-x  2 www-data root  4096 Nov 10 21:07 cache/

Also confirming vendor/ directory:
drwxr-xr-x 13 root     root  4096 Nov 11 03:28 vendor/

Within the project directory, output .env file set up:
root@e2fall2019:/var/www/html/e2/zipfoods# cat .env
APP_NAME='ZipFoods'
APP_URL='http://zipfoods.janenycxo.me'

DB_NAME='myapp'
DB_USERNAME='root'
DB_USERNAME=''

These all check out correctly, but http://zipfoods.janenycxo.me does not deploy. 
Meanwhile, these pages seem to be working:
http://zipfoods.janenycxo.me/about
http://zipfoods.loc/
http://zipfoods.loc/products

Can you advise what seems to be preventing the page from loading correctly? I'm at a loss. 

Thank you!
Jane

**Comment by RGPhD** [comment]
Dear @janenycxo,

You can compare the code you wrote from the videos to  all of Professor @susanBuck's **zipfoods** files at <https://github.com/susanBuck/e2/tree/master/zipfoods>.  It might be a small syntax error like missing one character somewhere.  If all of the files are exactly the same besides our code for the ```missing.blade.php``` file then maybe it is a command you are entering when connected to Digital Ocean.

Robelyn

**Comment by RGPhD** [comment]
Dear @janenycxo,
Your home page, product page and missing.blade.php are all working on my browser.  The only thing missing is the css styling for the images.
Robelyn

**Comment by susanBuck** [comment]
Confirming @RGPhD's note - all appears functioning on my end:

http://zipfoods.janenycxo.me/
http://zipfoods.janenycxo.me/products
http://zipfoods.janenycxo.me/product?id=1
http://zipfoods.janenycxo.me/about
http://zipfoods.janenycxo.me/contact

Let us know if you're not seeing the same on your end.

**Comment by janenycxo** [comment]
It’s loading in chrome for me now too. I discovered it doesn’t seem to cooperate in explorer. That might be an ongoing issue, but now I know. Thank you!!
