### ISSUE TITLE
Blade syntax highlighting in VSCode

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e2-fall19#78]
I noticed a difference in color coding between my views files (white) and the video (red).
Is it because of the different operating systems? or am I missing something?
![color coding difference](https://user-images.githubusercontent.com/1045307/68724532-b20e9e80-0570-11ea-92b1-4206b91b44bc.png)

**Comment by susanBuck** [comment]
Good observation! 

To get Blade syntax highlighting, install this VSCode extension: [Laravel Blade Snippets](https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade).

Once it's installed, in **Settings > Extensions > Blade Configuration**, check off **Enable format blade file**

![image](https://user-images.githubusercontent.com/237711/68725213-b1cfcc80-058b-11ea-8121-4c56311e5d9b.png)

**Comment by anyav77** [comment]
Thank you!  It worked.
