### ISSUE TITLE
Error viewing products page

### ISSUE THREAD

**Issue by jeremiahazurin** [susanBuck/e2-fall19#79]
Hi, everyone:

I have an error when I click on my products page:
```
Fatal error: Uncaught Error: Call to undefined method App\Controllers\ProductController::about() in /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/vendor/susanbuck/e2core/src/App.php:56 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/public/index.php(15): E2\App->route() #1 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/vendor/susanbuck/e2core/src/App.php on line 56
```

This is what I have on that line in my `App.php` file

    public function route()
    {
        # Get the path
        $uri = '/'.substr($_SERVER['REQUEST_URI'], 1);
        if (isset($this->routes[$uri])) {
            $controllerName = "App\Controllers\\".$this->routes[$uri][0];
            $controller = new $controllerName($this);
            $method = $this->routes[$uri][1];
            return $controller->$method();
        } else {
            return $this->blade->view()->make('errors.404')->with(['app' => $this])->render();
        }
    }

Am I supposed to call the new `productscontroller.php` file? How?

**Comment by jeremiahazurin** [comment]
Hmm, I think i found an issue. in my routes file, i had
`
    '/products' => ['ProductController', 'about']
`
not 
`
    '/products' => ['ProductController', 'index']
`

my new error, then, is:
`
Fatal error: Uncaught Error: Call to undefined function App\Controllers\path() in /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/app/Controllers/ProductController.php:10 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/vendor/susanbuck/e2core/src/App.php(56): App\Controllers\ProductController->index() #1 /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/public/index.php(15): E2\App->route() #2 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/app/Controllers/ProductController.php on line 10
`

still troubleshooting but I think i found one of many issues showing the product page

**Comment by jeremiahazurin** [comment]
I've concluded that the problem is in productcontroller.php. i can't dump the products.json files so i therefore can't load it. it's in my database folder but for some reason it's not showing

**Comment by shcantrell** [comment]
Hi - @jeremiahazurin.

I'm not the best at helping in a forum, but I am going to try, so forgive me if I only frustrate you more.

Do you mind including all of the code you have in ProductController.php file or point to your GitHub instance of it?

**Comment by jeremiahazurin** [comment]
Thanks! [Here](https://github.com/jeremiahazurin/e2/blob/master/zipfoods/app/Controllers/ProductController.php) it is.

When i remove
`
 $products = new Products($this->app->path('database/products.json'));
        return $this->app->view(
            'products.index',
            ['products' => $products->getAll()]
`
i can return regular text, but when i include the above, i get errors. so something tells me that the above code is not meshing well with something else. i just don't know what it is!

**Comment by shcantrell** [comment]
You are going to the products page by entering the path directly in the adddress bar or by a link?

**Comment by jeremiahazurin** [comment]
Link. I just tried by address bar and same null results

**Comment by shcantrell** [comment]
Okay- I'm battling with it, but that doesn't mean much - lol. I'll let you know if I figure something out. :)

**Comment by shcantrell** [comment]
Okay, I was able to troubleshoot for certain that in your ProductController.php file is not referencing the index.blade.php file witihn the views/products folders.

To troubleshoot, I simplified the ProductController.php to:

```php
<?php
namespace App\Controllers;

use App\Products;

class ProductController extends Controller
{
    public function index()
    {
        $products = new Products($this->app->path('database/products.json'));

        return $this->app->view('products.index');
   }
}
```

And simplifield the views/product/index.blade.php file to `Test`, and the error still appeared.

I decided to create a brand new index.blade.php file and placed "`Test` in the content and it worked.

Believing something was wrong with the old file, I copied the original code into the new file. Guess what - it did not work. 

So...THAT MEANT there was something going on with the code in the views/product/index.blade.php file. Keep in mind, you still get an error message, even if you comment the code out. The code has to be completely removed or the error message appears.

To troubleshoot again, I added the "bad" code into the file one section at a time.

It worked up to this point:

```php
@extends('templates.master')

@section('title')
{{ $app->config('app.name') }}
@endsection

@section('content')
<h2>All Products</h2>
@endsection
```

SOOOOOO - these guys are the culprit. See how you can rewrite this part of the code to show the product.

```php
@foreach
($products as $product)
{{$product['name']}}
@endforeach
```

**Comment by susanBuck** [comment]
(Great troubleshooting process/advise @shcantrell!)

**Comment by jeremiahazurin** [comment]
Thank you @shcantrell ! If views/product/index.blade.php is the problem, i'm still getting an error after copying and pasting your code to test it out. my error message says 
```
/Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/app/Controllers/ProductController.php on line 10
```

This is what my productcontroller.php file is:
```<?php
namespace App\Controllers;
use App\Products;
class ProductController extends Controller
{
    public function index()
    {
        $products = new Products($this->app->path('database/products.json'));
        return $this->app->view('products.index');
    }
}
```

and this is what my views/product/index.blade.php is:
```@extends('templates.master')
@section('title')
{{ $app->config('app.name') }}
@endsection
@section('content')
test
@endsection```

if i remove
```
 $products = new Products($this->app->path('database/products.json'));```

from the productcontroller.php file, it runs fine. so i think the problem is the above code?

**Comment by shcantrell** [comment]
I am not sure why the new code is not working. 

Is the "bad" code in the blade file still, just commented out? That will still output an error.

I am stumped.

**Comment by susanBuck** [comment]
fyi - taking a look at this locally now. Will follow-up shortly.

**Comment by susanBuck** [comment]
@jeremiahazurin - Can you update your repo with the latest changes?

**Comment by susanBuck** [comment]
I ran your code from your most recent commit...

After fixing `/views/products/index.php` per @shcantrell's notes above, the `/products` route loads in my tests.

![image](https://user-images.githubusercontent.com/237711/68884271-d7221f00-06e0-11ea-8e7f-23a233468376.png)

Is it still not working on your end @jeremiahazurin? If so, can you share the exact error message again? Up above, you reported it as:

```
/Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/app/Controllers/ProductController.php on line 10
```

..but this feels truncated. Is there any text before/after this?

**Comment by jeremiahazurin** [comment]
Hi, sorry, just got back from work + an exam!

anyways, i updated my repo with the latest changes which was just adding the following code to line 10 of `productcontroller.php`:
```
$products = new Products($this->app->path('database/products.json'));
```

and this is what i got after refreshing the products page:
```
Fatal error: Uncaught Error: Call to undefined method E2\App::path() in /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/app/Controllers/ProductController.php:10 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/vendor/susanbuck/e2core/src/App.php(56): App\Controllers\ProductController->index() #1 /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/public/index.php(15): E2\App->route() #2 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/app/Controllers/ProductController.php on line 10
```

**Comment by susanBuck** [comment]
np!

Within your zipfoods directory can you run `composer info` and report back on what version of e2core you have?

For example, here's why my output looks like:
```
susanbuck/e2core              0.1.5   Practice framework for CSCI E-2
```

The reason I ask is because when I run your code locally it runs w/o error, so I don't think it's specific to code in the project... I'm wondering if there's some dependency/setup issue.

**Comment by susanBuck** [comment]
Follow-up: I was just looking at the release history for e2core and I didn't add the `path` method until v0.1.2. If you're running a version older than that, that would explain why you're getting the error `Call to undefined method E2\App::path()`.

e2core is currently at 0.1.5 so if you're seeing a version less than this, run `composer update` to grab the latest.

(For reference, check out the *Part 1 Housekeeping* videos for Weeks 10 and 11 where I discuss running `composer update` to grab the latest changes to the e2core.)

**Comment by jeremiahazurin** [comment]
Will do, thank you! I'm about to enter one more exam in a few minutes but I will troubleshoot soon after. Thank you!

**Comment by jeremiahazurin** [comment]
hi, sorry for the tardiness. had work + an exam yesterday. anyways, i think that might have been the issue (v0.1.2 vs v0.1.5). 
<img width="872" alt="Screen Shot 2019-11-16 at 11 01 26" src="https://user-images.githubusercontent.com/16971379/68995878-a668f380-0860-11ea-969a-b47e57a5f484.png">
 I updated it so I will troubleshoot today and get back to you. Thanks everyone!

**Comment by jeremiahazurin** [comment]
So I'm as far as the CSS editing at the end of Part 3 but am stumped on why I have an error with linking each product to a separate page (line 12):
<img width="744" alt="Screen Shot 2019-11-18 at 22 16 19" src="https://user-images.githubusercontent.com/16971379/69113462-0faf5900-0a51-11ea-8f86-4728dd3f53bd.png">
Each of my links on my product page are linked in the sense that they are clickable but don't actually direct to a page.

**Comment by philyuska** [comment]
Hi, i had the same/similar issue, take a look at [this link](https://github.com/susanBuck/e2-fall19/issues/74) and see if this helps

Cheers

**Comment by jeremiahazurin** [comment]
> Hi, i had the same/similar issue, take a look at [this link](https://github.com/susanBuck/e2-fall19/issues/74) and see if this helps
> 
> Cheers

Thank you so much @philyuska! I **finally** finished this part. Last week was a doozy. Thanks everyone!!!!!!!!
