### ISSUE TITLE
Github SSH test - Permission denied (publickey)

### ISSUE THREAD

**Issue by RGPhD** [susanBuck/e2-fall19#8]
Dear Professor @susanBuck and classmates,

I am getting the same output message as @lindsaymshepard on the ssh test: 

**```Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts. git@github.com: Permission denied (publickey).```**

After trying suggestions by Professor @susanBuck from Lindsay’s issue post and following the troubleshooting in the notes and video for Windows 10, I still received the same output message.  Even though I was not receiving the same output message as described in the video, I did have to change the *Advanced* setting of **Disable inheritance** so it would read **Enable inheritance**.  This gave me two options for which I tried running the ssh test utilizing both options:

Could this an issue causing the error output message and which of the two is the preferred setting?

I then deleted all files for ssh on my PC and all of the Github keys I created and started the entire process, from the beginning, for a third time.  Again, I received the same output message.  I did notice in the troubleshooting video that Professor Susan’s ssh file was directly after her username:
```C:\Users\Susan\ssh```
My ssh file is at the location:
```C:\Users\DrRGa\%homepath%.ssh```
Could this be an issue causing the error output message?  I did move the file for my second run at the test, but that did not fix my error.

Entering the v (verbose) flag command  ssh -vT git@github.com  I get the output below:

DrRGa@LAPTOP-IU48L1LB MINGW64 ~
$ ssh -vT git@github.com
OpenSSH_8.0p1, OpenSSL 1.1.1c  28 May 2019
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to github.com [140.82.114.3] port 22.
debug1: Connection established.
debug1: identity file /c/Users/DrRGa/.ssh/id_rsa type -1
debug1: identity file /c/Users/DrRGa/.ssh/id_rsa-cert type -1
debug1: identity file /c/Users/DrRGa/.ssh/id_dsa type -1
debug1: identity file /c/Users/DrRGa/.ssh/id_dsa-cert type -1
debug1: identity file /c/Users/DrRGa/.ssh/id_ecdsa type -1
debug1: identity file /c/Users/DrRGa/.ssh/id_ecdsa-cert type -1
debug1: identity file /c/Users/DrRGa/.ssh/id_ed25519 type -1
debug1: identity file /c/Users/DrRGa/.ssh/id_ed25519-cert type -1
debug1: identity file /c/Users/DrRGa/.ssh/id_xmss type -1
debug1: identity file /c/Users/DrRGa/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.0
debug1: Remote protocol version 2.0, remote software version babeld-dae25663
debug1: no match: babeld-dae25663
debug1: Authenticating to github.com:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8
debug1: Host 'github.com' is known and matches the RSA host key.
debug1: Found key in /c/Users/DrRGa/.ssh/known_hosts:1
Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /c/Users/DrRGa/.ssh/id_rsa
debug1: Will attempt key: /c/Users/DrRGa/.ssh/id_dsa
debug1: Will attempt key: /c/Users/DrRGa/.ssh/id_ecdsa
debug1: Will attempt key: /c/Users/DrRGa/.ssh/id_ed25519
debug1: Will attempt key: /c/Users/DrRGa/.ssh/id_xmss
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,rsa-sha2-512,rsa-sha2-256,ssh-dss>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /c/Users/DrRGa/.ssh/id_rsa
debug1: Trying private key: /c/Users/DrRGa/.ssh/id_dsa
debug1: Trying private key: /c/Users/DrRGa/.ssh/id_ecdsa
debug1: Trying private key: /c/Users/DrRGa/.ssh/id_ed25519
debug1: Trying private key: /c/Users/DrRGa/.ssh/id_xmss
debug1: No more authentication methods to try.
git@github.com: Permission denied (publickey).

Entering the identity command  ssh -T -i %homepath%/.ssh/e2 git@github.com  I get the output below:

DrRGa@LAPTOP-IU48L1LB MINGW64 ~
$ ssh -T -i %homepath%/.ssh/e2 git@github.com
Warning: Identity file %homepath%/.ssh/e2 not accessible: No such file or directory.
Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
git@github.com: Permission denied (publickey).

I scanned the output and I have not been able to locate the source of the problem.  Does anyone have suggestions?

Thank you in advance,
Robelyn

P.S. I will attach a screenshot of the settings for the config file that also show my path below.
![Capture config settings](https://user-images.githubusercontent.com/54469368/64902643-07f1c380-d660-11e9-8d4e-f6e72addbe83.JPG)

P.P.S. I am going to try my key at DigitalOcean to see if it is only an issue with GitHub.

**Comment by philyuska** [comment]
Hi Robelyn,

I think you are currect when you

**Comment by philyuska** [comment]
Hi Robelyn,

On windows, %homepath% is an environment variable that points to your windows home directory. For example on my computer %homepath% is

set | grep HOMEPATH
`HOMEPATH=\Users\Phil`

>cd %HOMEPATH%/.ssh

>C:\Users\Phil\.ssh
>ll
>total 22
>drwxr-xr-x 1 Phil    0 Sep 12 03:22 ./
>drwxr-xr-x 1 Phil    0 Sep 12 03:17 ../
>-rw-r--r-- 1 Phil   23 Sep 12 03:22 config
>-rw-r--r-- 1 Phil 1675 Sep 12 03:21 e2
>-rw-r--r-- 1 Phil  402 Sep 12 03:21 e2.pub
>-rw-r--r-- 1 Phil 2340 Sep 14 09:17 known_hosts

You should see a similar result if you were to run the same commands in Commander.
If not you might want to revisit the Notes section on [Generating the SSH Keys](https://hesweb.dev/e2/notes#/git/github?jump=generate-ssh-keys-on-your-computer)

**Comment by RGPhD** [comment]
Dear @philyuska,

I see all my files like yours except my homepath is included in my SSH path as reflected below:
```C:\Users\DrRGa\%homepath%.ssh```

I will revisit the section you recommended, although I have followed it step by step 4 times.  It doesn't hurt to try again.  Do you happen to know how I can get my path to read like yours?  As aforementioned, Professor Susan's path is ```C:\Users\Susan\ssh```  ... just like your path.

Thank you,
Robelyn

**Comment by susanBuck** [comment]
Hi @RGPhD - I'm looking at the details of your post now. Any chance you're online? Maybe we could connect via Zoom and walk through the steps together. If not, I'll follow up shortly with some thoughts/suggestions.

**Comment by susanBuck** [comment]
@RGPhD - 
Let's try using the default SSH key name (which is `id_rsa`), because that will eliminate the need for messing with the SSH config file. Maybe that will help narrow things down and at least get you rolling forward with Github access. 

To do this, I first want to ascertain if you have an existing default key.

List the contents of your computer's .ssh directory.

Do you see a file called `id_rsa` and `id_rsa.pub`?

If you do, we'll use that existing key pair.

Copy the contents of `id_rsa.pub` into a new key in Github, then test your SSH connection to Github. Always confirm you're using the public key in this step, which starts with `ssh-rsa` and ends with your email address. 

If you don't already have a `id_rsa` / `id_rsa.pub` key pair, generate it:

```bash
ssh-keygen -t rsa -C "your_email@example.com"
```

When going through the generation steps, though, do not enter a custom key name. When it asks for the name/path just leave it blank and hit enter.

When you're done with this, *now* you should have a `id_rsa.pub` key you can add in Github, and then test your SSH connection.

Knock on wood, that should at least get you connected. : )

side note: Great breakdown of your troubleshooting steps and level of detail in your initial post. 👍

**Comment by RGPhD** [comment]
Dear Professor @susanBuck,

Your perfect instructions worked and I received the successful output message:

```Hi RGPhD! You've successfully authenticated, but GitHub does not provide shell access.``` 

Thank you very much @philyuska and @susanBuck, 

Robelyn

**Comment by susanBuck** [comment]
Fantastic! Glad it's sorted out.

**Comment by olamyde** [comment]
This work for me too. thanks all.
