### ISSUE TITLE
SQLSTATE[HY000] [2002] Error with local setup of ZipFoods

### ISSUE THREAD

**Issue by Matt49** [susanBuck/e2-fall19#80]
I'm behind in classwork and am just setting up the ZipFoods app on my local server. I've checked through the steps several times and can't see where I went wrong. Does the error message reveal anything to anyone? It makes me think there is something related to databases going on, but I have no idea why. Thanks.

```
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/vendor/susanbuck/e2core/src/Database.php:22 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/vendor/susanbuck/e2core/src/App.php(59): E2\Database->__construct(NULL, 'myapp', 'root', NULL, 'utf8mb4') #1 /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/public/index.php(12): E2\App->__construct() #2 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/vendor/susanbuck/e2core/src/Database.php on line 22
```

**Comment by Matt49** [comment]
Sorry about the long error message. Here is is in a more readable format:

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/vendor/susanbuck/e2core/src/Database.php:22 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/vendor/susanbuck/e2core/src/App.php(59): E2\Database->__construct(NULL, 'myapp', 'root', NULL, 'utf8mb4') #1 /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/public/index.php(12): E2\App->__construct() #2 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/vendor/susanbuck/e2core/src/Database.php on line 22

**Comment by susanBuck** [comment]
Hi @Matt49 - Your suspicions are correct - this is coming from code I added to the framework that is attempting to make a database connection (relevant to this week's material).

I've recently put a patch into the framework core that prevents it from attempting to connect to a database until you explicitly attempt to do. That way, it will work without error if you haven't yet set up your database.

Can you run `composer update` in your project so it pulls down the latest version of the `e2core`? It should resolve the error you're seeing. If not, let me know!

**Comment by Matt49** [comment]
I suspected it might have to do with how far behind I've gotten:)

That worked @susanBuck. Thanks!
