### ISSUE TITLE
composer update - warning: LF will be replaced by CRLF

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e2-fall19#82]
I got a warning when running the composer update:

```
C:\xampp\htdocs\e2\zipfoods (master){hg}
λ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 5 updates, 0 removals
  - Updating symfony/var-dumper (v4.3.7 => v4.3.8): Loading from cache
  - Updating symfony/debug (v4.3.7 => v4.3.8): Loading from cache
  - Updating symfony/translation (v4.3.7 => v4.3.8): Loading from cache
  - Updating symfony/finder (v4.3.7 => v4.3.8): Loading from cache
  - Updating susanbuck/e2core (0.1.2 => 0.1.5): Downloading (100%)
Writing lock file
Generating autoload files

warning: LF will be replaced by CRLF in zipfoods/composer.lock.
The file will have its original line endings in your working directory
C:\xampp\htdocs\e2\zipfoods (master){hg}
λ
```

I just want to make sure it's normal for Windows, as I didn't see it in the video.

**Comment by susanBuck** [comment]
Hi @anyav77 -

That's expected/okay.

It has to do with how line endings are encoded in different systems.

Earlier in the semester when I had you set up Git, [I instructed Window's users to run this Git config](https://hesweb.dev/e2/notes#/git/setup?jump=initial-git-configuration):

```
git config --global core.autocrlf true
```

Here's what that setting does:

>> core.autocrlf = true This means that Git will process all text files and make sure that CRLF is replaced with LF when writing that file to the object database and turn all LF back into CRLF when writing out into the working directory. This is the recommended setting on Windows because it ensures that your repository can be used on other platforms while retaining CRLF in your working directory.

Reference:
* https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings
* https://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/

**Comment by anyav77** [comment]
Thank you!
