### ISSUE TITLE
Error with Database Connection

### ISSUE THREAD

**Issue by MPVaccaro** [susanBuck/e2-fall19#83]
I have gotten stuck on the Week 11, Part 5 Video where we make the database connection with the framework and expect to see the __"connection successful'__ message on the ```http://zipfoods.loc/practice``` page.

This is the error message I get:
 ```Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/app/Controllers/AppController.php:57 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/vendor/susanbuck/e2core/src/App.php(106): App\Controllers\AppController->practice() #1 /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/public/index.php(15): E2\App->route() #2 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/app/Controllers/AppController.php on line 57```

This is my .env file:

```APP_NAME='ZipFoods'
APP_URL='http://zipfoods.loc'

DB_Host='localhost'
DB_NAME='zipfoods'
DB_USERNAME='root'
DB_USERNAME=''

```

Here is the code from my ___AppController.php___ file: (Line 57 starts with  ```throw new```)
```php
<?php
namespace App\Controllers;

class AppController extends Controller
{
    /**
     *
     */
    public function index()
    {
        $welcomes = ['Welcome', 'Aloha!', 'Welkom', 'Bienvenidos', 'Bienvenu', 'Welkomma'];
        
        return $this->app->view('index', [
            'welcome' => $welcomes[array_rand($welcomes)]
        ]);
    }
    
    public function contact()
    {
        return $this->app->view('contact');
    }
    
     public function about()
    {
        return $this->app->view('about');
    }
    

    public function practice()
        {
        # local username: "root"
        # local password: "" (nothing, empty string)
        
        # Set up all the variables we need to make a connection
        
        $host = $this->app->env('DB_HOST');
        $database = $this->app->env('DB_NAME');
        $username = $this->app->env('DB_USERNAME');
        $password = $this->app->env('DB_PASSWORD');
        $charset = $this->app->env('DB_CHARSET', 'utf8mb4');

        # DSN (Data Source Name) string
        # contains the information required to connect to the database
        $dsn = "mysql:host=$host;dbname=$database;charset=$charset";

        # Driver-specific connection options
        $options = [
            \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION,
            \PDO::ATTR_DEFAULT_FETCH_MODE => \PDO::FETCH_ASSOC,
            \PDO::ATTR_EMULATE_PREPARES => false,
        ];

        try {
            # Create a PDO instance representing a connection to a database
            $pdo = new \PDO($dsn, $username, $password, $options);
        } catch (\PDOException $e) {
            throw new \PDOException($e->getMessage(), (int)$e->getCode());
        }

        dump('Connection succesful!');
        }
}
```
Notes: 
1. I ran ```Composer Info``` and my e2 core is up to date, Version 0.1.5 
2. My XAMPP MySQL Database is running.
3. I set up the zipfoods database as directed, and it seems to be working fine.
4. The test ```php 
public function practice()  {
return "You are looking at the practice route"; 
}``` worked.

**Comment by susanBuck** [comment]
Hi Mary,

In your environment file,

```
DB_Host='localhost'
```

Should be:

```
DB_HOST='localhost'
```

If that doesn't fix it, let me know!

**Comment by MPVaccaro** [comment]
Thank you! That solved the problem.
