### ISSUE TITLE
Fatal error...Call to undefined method E2\App::errorsExist()

### ISSUE THREAD

**Issue by baugh20s** [susanBuck/e2-fall19#85]
When I added the if errorsExist statement to my show view, I started getting a fatal error about an undefined method. It appears as soon as I try to get to a product details page. I've pushed my code to GitHub so it should be up to date. I'm wondering if something went awry with the Laravell framework. Anyone else running into this? 

This is the error:

![Screen Shot 2019-11-19 at 9 06 54 PM](https://user-images.githubusercontent.com/20144373/69202888-e7872f00-0b10-11ea-9324-0da05b6d7019.png)

**Comment by susanBuck** [comment]
Within your zipfoods project run `composer info` - this will report back on the version numbers of all of your dependencies.

What version is `susanbuck/e2core` showing? 

If you have an older version, it's possible that the `errorsExist` method was not yet added.

If in doubt, you can always run `composer update` to make sure you've got the latest version.

**Comment by RGPhD** [comment]
Dear @baugh20s and Professor @susanBuck,

I had the same **fatal error** message; running ```compser update``` corrected the issue on my local server.

Robelyn

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any problems are still pending.

**Comment by baugh20s** [comment]
The composer update command fixed it :)
