### ISSUE TITLE
changing user psw, production server sequence

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e2-fall19#94]
1. I mistakenly set up the user psw the same as SQL psw.  Is there a way to change it?
2. I installed the database prior to pulling the git content and running composer update --no-dev.  Is it a problem?

**Comment by anyav77** [comment]
It probably is a problem, as I'm getting an error:
![fatal error](https://user-images.githubusercontent.com/1045307/69931294-8d288f80-147b-11ea-9ab7-013bf58413d2.png)

^ "SELECT * FROM products ORDER BY id DESC"
^ "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'zipfoods.products' doesn't exist"

Fatal error: Uncaught Error: Call to a member function fetchAll() on null in /var/www/html/e2/zipfoods/vendor/susanbuck/e2core/src/Database.php:46 Stack trace: #0 /var/www/html/e2/zipfoods/app/Controllers/ProductController.php(14): E2\Database->all('products') #1 /var/www/html/e2/zipfoods/vendor/susanbuck/e2core/src/App.php(225): App\Controllers\ProductController->index() #2 /var/www/html/e2/zipfoods/public/index.php(15): E2\App->route() #3 {main} thrown in /var/www/html/e2/zipfoods/vendor/susanbuck/e2core/src/Database.php on line 46

**Comment by susanBuck** [comment]
This command should allow you to update your password:

```
SET PASSWORD FOR 'e2'@'localhost' = PASSWORD('your-password-here');
```

Ref: https://linuxacademy.com/blog/linux/changing-mysql-user-password/

I don't believe there should be any problems if you created the DB before updating the code base.
