### ISSUE TITLE
Week 14, Part 2 - Error when running composer create-project

### ISSUE THREAD

**Issue by lindsaymshepard** [susanBuck/e2-fall19#96]
Last login: Mon Dec  2 14:20:41 on console
LindsayShepard@Lindsays-MBP ~ % cd /Applications/XAMPP/xamppfiles/htdocs/e2
LindsayShepard@Lindsays-MBP e2 % composer create-project --prefer-dist lindsayshepard/e2framework MyApp 
Cannot create cache directory /Users/LindsayShepard/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache

                                                                            
  [InvalidArgumentException]                                                
  Could not find package lindsayshepard/e2framework with stability stable.  
                                                                            

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

LindsayShepard@Lindsays-MBP e2 % 

I received this notice as soon as I ran the first thing to do in the part 2 video.

**Comment by susanBuck** [comment]
Hi @lindsaymshepard -

You shouldn't swap in your Github username in this instance. `susanBuck/e2framework` is the template from which the project is being created from, so the command should be:

```
composer create-project --prefer-dist susanBuck/e2framework MyApp
```

**Comment by lindsaymshepard** [comment]
Cannot create cache directory /Users/LindsayShepard/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Installing susanbuck/e2framework (0.1.4)
Cannot create cache directory /Users/LindsayShepard/.composer/cache/files/, or directory is not writable. Proceeding without cache
  - Installing susanbuck/e2framework (0.1.4): Downloading (100%)         
Created project in MyApp
Cannot create cache directory /Users/LindsayShepard/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /Users/LindsayShepard/.composer/cache/files/, or directory is not writable. Proceeding without cache
> php -r "copy('.env.example', '.env');"
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 22 installs, 0 updates, 0 removals
  - Installing doctrine/inflector (1.3.1): Downloading (100%)         
  - Installing psr/log (1.1.2): Downloading (100%)         
  - Installing symfony/debug (v4.3.8): Downloading (100%)         
  - Installing symfony/translation-contracts (v1.1.7): Downloading (100%)         - Installing symfony/polyfill-mbstring (v1.12.0): Downloading (100%)         
  - Installing symfony/translation (v4.3.8): Downloading (100%)         
  - Installing nesbot/carbon (2.26.0): Downloading (100%)         
  - Installing psr/simple-cache (1.0.1): Downloading (100%)         
  - Installing psr/container (1.0.0): Downloading (100%)         
  - Installing illuminate/contracts (v5.8.35): Downloading (100%)         
  - Installing illuminate/support (v5.8.35): Downloading (100%)         
  - Installing symfony/finder (v4.3.8): Downloading (100%)         
  - Installing illuminate/filesystem (v5.8.35): Downloading (100%)         
  - Installing illuminate/container (v5.8.35): Downloading (100%)         
  - Installing illuminate/events (v5.8.35): Downloading (100%)         
  - Installing illuminate/view (v5.8.35): Downloading (100%)         
  - Installing vlucas/phpdotenv (v2.3.0): Downloading (100%)         
  - Installing symfony/polyfill-php72 (v1.12.0): Downloading (100%)         
  - Installing symfony/var-dumper (v4.3.8): Downloading (100%)         
  - Installing philo/laravel-blade (v3.1): Downloading (100%)         
  - Installing dflydev/dot-access-data (v2.0.0): Downloading (100%)         
  - Installing susanbuck/e2core (0.1.6): Downloading (100%)         
symfony/translation suggests installing psr/log-implementation (To use logging capability in translator)
symfony/translation suggests installing symfony/config
symfony/translation suggests installing symfony/yaml
illuminate/support suggests installing moontoast/math (Required to use ordered UUIDs (^1.1).)
illuminate/support suggests installing ramsey/uuid (Required to use Str::uuid() (^3.7).)
illuminate/support suggests installing symfony/process (Required to use the composer class (^4.2).)
illuminate/filesystem suggests installing league/flysystem (Required to use the Flysystem local and FTP drivers (^1.0).)
illuminate/filesystem suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (^1.0).)
illuminate/filesystem suggests installing league/flysystem-cached-adapter (Required to use the Flysystem cache (^1.0).)
illuminate/filesystem suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (^1.0).)
illuminate/filesystem suggests installing league/flysystem-sftp (Required to use the Flysystem SFTP driver (^1.0).)
symfony/var-dumper suggests installing ext-intl (To show region name in time zone dump)
symfony/var-dumper suggests installing symfony/console (To use the ServerDumpCommand and/or the bin/var-dump-server script)
Generating autoload files
LindsayShepard@Lindsays-MBP e2 % 

Oh ok! I also ran it and it does generate files but I still get the cache directory error- is that ok?

**Comment by susanBuck** [comment]
Yup, it's okay! That message just means that Composer won't be able to write any cache files, but, as it notes, it will "Proceed without cache". It'll still work, Composer just can't be as efficient as it could be if it had access to its cache. You can ignore the message, or if you want to fix it, you can run this command:

```
sudo chown -R $USER $HOME/.composer
```
