### ISSUE TITLE
Error Validating Radio Buttons

### ISSUE THREAD

**Issue by chantelledmello** [susanBuck/e2-fall19#97]
Hi prof, I'm running into a strange error when I try to validate the radio buttons in my form for my final P4 game. 

This is the code that I'm running as part of my ```saveResults()``` function: 

```php
public function saveResults()
    {
        $this->app->validate([
            'result' => 'required',
        ]);

        // Grab player input
        $user = $this->app->input('result');

        // Create array with all possible throws
        $throws = ['rock', 'paper', 'scissors'];
        $computer = $throws[array_rand($throws)];

        // More code after this...

}
```

for this form in my ```index.blade.php``` view file:

```html
<form method='GET' action='/save-results'>
        <div>
          <input type="radio" name="result" value="rock" id="rock"> <label for="rock"> rock </label>
          <input type="radio" name="result" value="paper" id="paper"> <label for="paper"> paper </label>
          <input type="radio" name="result" value="scissors" id="scissors"> <label for="scissors"> scissors </label>
        </div>
        <button type='submit'> Let's Play </button>
        </form>
```

And this is the error that it throws: 

<img width="1052" alt="Screen Shot 2019-12-05 at 9 35 55 PM" src="https://user-images.githubusercontent.com/26146422/70287919-08a17e00-17a7-11ea-8301-00571f2c82f4.png">

If I comment out the validation block of code, it works perfectly and I get my results printed onto the page as such:

<img width="585" alt="Screen Shot 2019-12-05 at 9 36 07 PM" src="https://user-images.githubusercontent.com/26146422/70287938-148d4000-17a7-11ea-9e62-dce7261e221b.png">

I tried to look through the notes to see if there was anything about using the built-in validate method for radio buttons but haven't found anything.

**Comment by chantelledmello** [comment]
Hi @susanBuck! Any luck with this? 🙈

**Comment by susanBuck** [comment]
FYI Taking a look now.

**Comment by susanBuck** [comment]
Can you update your code repo with the latest changes? I cloned your project locally, but I'm seeing some different code from what you described above.

**Comment by chantelledmello** [comment]
Hi @susanBuck just did! Sorry for the delay

**Comment by susanBuck** [comment]
Hi @chantelledmello -

Dug into this and the problem was my fault - there was a bug in the e2framework. Apologies for that! 

The problem was the validator was only set up to to check $_POST data, not $_GET data (your form was submitting via GET).

I released a patch to fix the issue.

Run `composer update` in your project to get the update.

It should update `e2core` to `v0.1.9`. Example:

```bash
e2/p4 (master) ! $ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating susanbuck/e2core (0.1.8 => 0.1.9): Downloading (100%)         
Writing lock file
Generating autoload files
```

If needed, you can check the version numbers of your dependencies by running `composer info`.

**Comment by chantelledmello** [comment]
Thank you for getting into it so quickly! Much appreciated! Will run the update asap

**Comment by susanBuck** [comment]
Closing this out as I believe the issue should be resolved, but feel free to re-open or start a new thread if it's still not working.
