### ISSUE TITLE
project 4 homepage showing directory files

### ISSUE THREAD

**Issue by baugh20s** [susanBuck/e2-fall19#99]
When I go to my local p4 project, I'm seeing the directory of files (screenshot below). I know I've seen this issue before either in previous classes or in the issues post but having trouble finding the solution - hoping someone can point me to notes or a post!

For the project, I've done the following so far:
1. Run: `composer create-project --prefer-dist susanBuck/e2framework p4`
2. Added a virtual host entry (screenshot attached)
3. Created a host (screenshot attached)
4. Edited the .env file (screenshot attached)
5. Restarted the servers

Troubleshooting steps I've taken:
- I did double-check the virtual host entry, host, and .env file so I think those are set up correctly.
- I also ran composer update just in case

![local p4](https://user-images.githubusercontent.com/20144373/70381205-70290c00-1914-11ea-81cd-6886b7ff041c.png)
![env](https://user-images.githubusercontent.com/20144373/70381206-70290c00-1914-11ea-983a-9e32fc33837c.png)
![vhosts](https://user-images.githubusercontent.com/20144373/70381207-70290c00-1914-11ea-9cf2-45a5923fc2e7.png)
![hosts](https://user-images.githubusercontent.com/20144373/70381208-70290c00-1914-11ea-81e4-3ab5b68e7ebe.png)

**Comment by MPVaccaro** [comment]
Is your local virtual host for p4 set to ```/public```?
(The prior projects we set up were not set to public, but zipfoods and our p4 project should be set to end in ```/public``` so that _public_ will be the folder that opens by default:
```
<VirtualHost *:80>
    ServerName zipfoods.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/public
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/public>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
        Require all granted
    </Directory>
</VirtualHost>
```

**Comment by susanBuck** [comment]
+1 to @MPVaccaro's answer. 

If that doesn't do the trick - let us know.
